JuliaDiff/ChainRules.jl

.gitignore
.travis.yml
Project.toml
REQUIRE
docs/Project.toml
docs/make.jl
docs/src/index.md

Before you get too excited, this PR does not add _documentation_, it adds documentation _setup_. I've generated the necessary Documenter keys for GitHub and Travis, so this should get everything up and running.
I've also included ~~two~~ three unrelated changes as separate commits: remove 0.7 from Travis since we claim not to support it, add a Project.toml file, and add a missing dependency to REQUIRE.

Add documentation setup

---

src/rules/broadcast.jl
test/runtests.jl

There was an issue in the reverse mode rule for `broadcast` which has been fixed. Also the tests have been updated to reflect the new names for things.

Fix a bug and the existing tests

---

src/rules.jl

I can modify `accumulate!`'s docstring to include a note about support for scalar `Δ` once the relevant change from #14 is merged

add docstrings for accumulate, accumulate! and store!

---

Project.toml
src/rules.jl
src/rules/linalg.jl
test/differentials.jl
test/rules.jl
test/rules/base.jl
test/rules/broadcast.jl
test/rules/linalg.jl
test/runtests.jl
test/test_util.jl

This is some initial work to set up systematic testing for `frule`s and `rrule`s. This initial work covers:
- Some utility functionality to make running finite-differencing straightforward. This depends on FDM.jl
- I've extended `accumulate!` very slightly to accomodate scalars. @jrevels I could use your input here, this might be totally inconsistent with what you have in mind.
- I've moved some tests around and established a nested testset with 1-1 mapping between `src` and `test` files.
- All `frule`s and `rrule`s in `linalg` are now covered as a demonstration of the functionality.
There are a few things that need to be addressed before I go about adding extra finite-differencing test-coverage (in a later PR) / before this could be merged:
- What have I got structurally wrong in this …

Initial finite differencing testing

---

src/ChainRules.jl
src/rules.jl
test/runtests.jl

Quality of life improvement. Currently this just exports the very basics, with minimal chance of name collision with other packages and/or user code.

Add some basic exports

---

src/rules/linalg/diagonal.jl
src/rules/linalg/symmetric.jl
test/rules/linalg/diagonal.jl

Currently these definitions are extending `rrule(::typeof(T), x)` where `T` is a type. However, `typeof(Diagonal) == UnionAll`, which means this is not defining the method it looks like it might be defining. The only reason this worked when originally implemented was that one of the `rrule` definitions was for `rrule(UnionAll, Matrix)` and the other for `rrule(UnionAll, Vector)`, so dispatch still worked.
This replaces these problematic `::typeof(T)`s with `::Type{<:T}`.

Fix rrules for Symmetric and Diagonal constructors

---

test/test_util.jl

Currently in the testing utilities we define an internal `cr_isapprox` function that mimics `isapprox` except we only accept a subset of the keyword arguments accepted by `isapprox`. Instead, we can just define methods for `isapprox` on ChainRules-defined types for the purposes of testing. That way we can more easily take arbitrary keyword arguments and get Test's special-cased pretty printing for `@test a ≈ b`.

Extend Base.isapprox instead of defining cr_isapprox

---

test/test_util.jl

Currently, if the check for all rules comparing approximately equal to their finite differencing counterparts fails, the test failure just tells you that `all(...)` was `false`. If we restructure it as a loop
over the results, a failure will display the actual values that were compared, which is much more informative.
While I was in here, I also changed the `map` directly below to a loop, since that's what the `map` was doing; the resulting vector of `nothing`s was not being used. It could just have well have been a `foreach`, but an explicit loop seems clearer.
I ran into this because, as it turns out, I'm real good at getting tests to fail when adding new stuff.

Reformat rrule_test for more informative output on failure

---

src/rules/blas.jl
test/rules/blas.jl

Implement sensitivities for `BLAS.gemm`

---

src/rules.jl
src/rules/linalg/factorization.jl
test/rules.jl
test/rules/linalg/factorization.jl

Now `Rule`s store two things: one callable thing, which is used for evaluating the rule, and one other thing, which can be `nothing` or a function with the signature `u(value, args...)` that evaluates the rule for the given arguments and adds the result to `value`, doing so in place when possible.
The advantage of this is that we can more easily define custom ways of accumulating the results of rules, and we can even share intermediate steps between the regular rule evaluation and custom updating. As a test/proof of concept, the `rrule` for `svd` now also has an updating function that handles `NamedTuple`s appropriately.
Fixes #39, but implemented before Lyndon made his suggestion.

Make Rules store a second function for updating

---

src/ChainRules.jl
src/rules/array.jl
test/rules/array.jl
test/runtests.jl

The stuff in Nabla's `src/sensitivities/array.jl`, which includes `reshape`, `hcat`, `vcat`, and `fill`.

Port more array-related derivatives from Nabla

---

src/rules/linalg/factorization.jl
test/rules/linalg/factorization.jl

This is a (mostly) direct port of the code from Nabla.

Add an rrule for the Cholesky decomposition

---

Project.toml
src/rules/linalg/dense.jl
test/rules/linalg/dense.jl

These are ported from Nabla.
WIP because:

Add rrules for binary linear algebra operations

---

src/rules.jl
test/rules.jl

We define `iterate` on them for convenience, and `getindex` provides a similar convenience for cases where you're not sure whether the rules resulting from a call to `rrule`/`frule` will be a `Tuple`. So instead of writing `partials isa Tuple ? partials[i] : partials`, you can now just write `partials[i]`.

Define `getindex` on rules

---

src/rules.jl
src/rules/mapreduce.jl
test/rules.jl

There are cases where you want to ensure that a call to `rrule` produced something before you proceed. In such cases, one can now use an internal function called `_checked_rrule`, which produces an informative error if `rrule` returns `nothing`.
One such case is exemplified in the second commit, which uses `_checked_rrule` inside of the `rrule` for `map`.

Add `_checked_rrule`, which errors if `rrule` returns `nothing`

---

src/rules.jl
test/rules.jl

This permits using `rrule(f, args...; kwargs...)` unconditionally and receiving `nothing` as expected rather than an error about `rrule` not taking keyword arguments.

Allow keyword arguments in the fallback rrule/frule methods

---

src/ChainRules.jl
src/rules/linalg/blas.jl

Currently some of the rules are calling `blascopy!` and `scal!` without qualification, which fails, since we haven't done a full `using` for the BLAS submodule. (We can do that later, but currently there's an export
conflict with LinearAlgebra itself.) So for now we can just selectively use the names.

Bring in BLAS names that are used without qualification

---

src/rules.jl
src/rules/base.jl
test/rules.jl

Currently, `@scalar_rule` generates `rrule` methods with no type constraints. This poses a problem for rules with different definitions that have not yet been implemented. For example, the rule for matrix
exponential is quite different from that for scalar exponential, but in the absence of an `rrule(::typeof(exp), ::AbstractMatrix)` method, the incorrect fallback generated by `@scalar_rule` is used.
To solve this, `@scalar_rule` now allows type constraints, e.g. `@scalar_rule(f(x::Complex), g(x))`, and it adds explicit `::Number` constraints to the generated methods if no such constraints are provided.

Ensure scalar_rule rules are Number typed

---

src/rulesets/Base/base.jl
test/rulesets/Base/base.jl

As `d/dx hypot(x,y) = x/hypot(x, y)` and `d/dy hypot(x,y) = y/hypot(x, y)`, I think that the rule for `hypot` was incorrect.

Fix hypot frule

---

src/rulesets/Base/base.jl

Before this, e.g. `frule(*, [1,2], Dual(1))` would return a non-nothing. This change helps avoid special casing this in a generic implementation of scalar diff.

Restrict the scalar multiplication rules to `Number`s

---

docs/Project.toml
docs/make.jl
docs/src/api.md
docs/src/getting_started.md
docs/src/index.md
src/ChainRules.jl

1. Right now the API docs don't render because `ChainRules.foo` has been moved to `ChainRulesCore.foo`
2. This PR essentially means we have a single set of docs for ChainRules and ChainRules core (https://github.com/JuliaDiff/ChainRulesCore.jl/issues/12)
Before:
After:

Fix documentation to use ChainRulesCore

---

src/ChainRules.jl
src/rulesets/Base/mapreduce.jl
src/rulesets/Statistics/statistics.jl
test/rulesets/Base/mapreduce.jl
test/rulesets/Statistics/statistics.jl
test/runtests.jl

- closes #75 
- sorry for the redundant naming, but it means the structure is internally consistent, and also it matched the actual stdlib structure so 🤷‍♂

Move `mean` rule to a Statistics ruleset folder

---

src/rulesets/Base/base.jl
test/rulesets/Base/base.jl

Is this right?
Should I have some type constraints somewhere 
or does `@scalar_rule` give me that for free?

add rules for constant returning zero and one function

---

src/rulesets/Base/base.jl
test/rulesets/Base/base.jl
test/rulesets/Base/broadcast.jl
test/rulesets/packages/SpecialFunctions.jl
test/runtests.jl
test/test_util.jl

Closes #76
and the mistakes found in #86 for incorrect acshc asec acsc, asecd acscd rules

Add FiniteDifferences based scalar rule tests

---

Project.toml
docs/src/getting_started.md
test/runtests.jl
test/test_util.jl

We access some of the internals of ChainRulesCore for testing purposes.
This changes that over to match the changes in
https://github.com/JuliaDiff/ChainRulesCore.jl/pull/35
That PR has to be merged first.
I have tested these together and they do work together.
Passing all tests.

Remove uses of add and mul from tests because they have been removed ChainRulesCore

---

src/rulesets/Base/base.jl
test/rulesets/Base/base.jl

Closes #88, also `hypot`. More minimal version of #55, we can address `hypot` for `VarArg` and complex input later.

Fix abs(::Complex)

---

README.md
docs/make.jl

This trick is taken from @fredrikekre's https://github.com/fredrikekre/Literate.jl/pull/75
I will rebase #103 ontop of this if we can get this in fairly quick

PR preview docs

---

src/rulesets/LinearAlgebra/structured.jl
test/rulesets/LinearAlgebra/structured.jl

ref https://github.com/JuliaDiff/ChainRules.jl/issues/52#issuecomment-531146406
Reading #103 and other source code, I suppose we are only defining `rrule`s for `Real` element types at the moment so didn't put `adjoint` in the definition. (By the way, if that's the case, I think it makes sense to mention it in #103.)

Add rrule for Diagonal * AbstractVector

---

docs/make.jl
docs/src/assets/chainrules.css
docs/src/index.md

Preview: http://www.juliadiff.org/ChainRules.jl/preview-PR103/
---
Old OP:
This will describe the post https://github.com/JuliaDiff/ChainRulesCore.jl/pull/30
world, so we won't merge this til after that then.
But reading this will help reviewers of that PR and 
https://github.com/JuliaDiff/ChainRules.jl/pull/91

introdocs + demo + instructions on writing good rules

---

Project.toml
src/rulesets/packages/NaNMath.jl
src/rulesets/packages/SpecialFunctions.jl

I believe this should solve #115 
From the [Requires.jl](https://github.com/MikeInnes/Requires.jl/blob/master/README.md) readme:
> In the @require block, or any included files, you can use or import the package, but note that you must use the syntax using .Gadfly or import .Gadfly, rather than the usual syntax. Otherwise you will get a warning about Gadfly not being in dependencies.

do using of at-required packages relative

---

Project.toml
src/rulesets/Base/broadcast.jl
src/rulesets/Base/mapreduce.jl
src/rulesets/LinearAlgebra/dense.jl
test/rulesets/Base/base.jl
test/runtests.jl
test/test_util.jl

Matches to https://github.com/JuliaDiff/ChainRulesCore.jl/pull/55
There is also a surprisingly large change to `hypot`'s tests
as they were AFAWCT nonsense.

Removes rules depending on casted

---

test/test_util.jl

Was this left on purpose? It assumes that differentials can be iterated, which broke integration tests in JuliaDiff/ChainRulesCore.jl#54.

remove comma in `test_scalar`

---

Project.toml
src/rulesets/Base/array.jl
src/rulesets/Base/base.jl
src/rulesets/Base/broadcast.jl
src/rulesets/Base/mapreduce.jl
src/rulesets/LinearAlgebra/blas.jl
src/rulesets/LinearAlgebra/factorization.jl
src/rulesets/Statistics/statistics.jl
test/rulesets/Base/array.jl
test/rulesets/Base/broadcast.jl
test/rulesets/LinearAlgebra/factorization.jl
test/runtests.jl
test/test_util.jl

- partner to https://github.com/JuliaDiff/ChainRulesCore.jl/pull/42
- ~is breaking~ Not now ChainrulesCore uses `@deprecate_binding`

Rename `DNE` -> `DoesNotExist`

---

Project.toml
src/rulesets/Base/base.jl
src/rulesets/packages/NaNMath.jl
src/rulesets/packages/SpecialFunctions.jl
test/rulesets/Base/base.jl

Work in progress for comments!

WIP: adding more rules and fixing old ones

---

test/rulesets/Base/base.jl

I think when we switch `atan2` tests to use `frule_test` and `rrule_test` we forgot to delete the old bad tests.
I think this is now tested well using 
https://github.com/JuliaDiff/ChainRules.jl/blob/3e6eee3228cf7b1be2ce35c4ddc87ca5a65b0a60/test/rulesets/Base/base.jl#L140-L148

remove old atan2 tests

---

Project.toml
src/rulesets/Base/base.jl

Ref https://github.com/JuliaDiff/ChainRulesCore.jl/pull/93

Add broadcast in the `frule` for `*`

---

docs/src/index.md

New docs,
major change is about  the pushforward now fused into the `frule`.

Doc updates for ChainRulesCore 0.5

---

docs/make.jl
docs/src/getting_started.md
docs/src/index.md

The information is in other sections,
and even if TODO, belongs in issues, rather than in docs.
It also just looks bad

Remove TODO sections in docs

---

docs/make.jl
docs/src/FAQ.md
docs/src/index.md
docs/src/writing_good_rules.md

I had been meaning to break the FAQ and Writing good Rules sections out into their own pages for ages.
Could potentially break out a bit more, but I think this is an improvement and it  gets harder if we want to think about moving out e.g. the direct usage example or part of the descriptions of the propagators.
Only change other than moving things is to the levels of headings.
To match the next structure.

Break up giant single page of docs

---

Project.toml
docs/src/index.md
src/ChainRules.jl
src/helper_functions.jl
src/rulesets/LinearAlgebra/factorization.jl
src/rulesets/LinearAlgebra/utils.jl
test/helper_functions.jl
test/rulesets/Base/base.jl
test/rulesets/Base/broadcast.jl
test/rulesets/LinearAlgebra/dense.jl
test/rulesets/LinearAlgebra/factorization.jl
test/runtests.jl
test/test_util.jl

- part of #151 
- Very WIP
- Currently presumes we have https://github.com/JuliaDiff/ChainRulesCore.jl/pull/107

Change SVD to use `Composite`

---

Project.toml
src/rulesets/LinearAlgebra/factorization.jl
test/rulesets/LinearAlgebra/factorization.jl

Change Cholesky to use `Composite`

---

.travis.yml
Project.toml
src/rulesets/Base/base.jl
src/rulesets/Base/broadcast.jl
src/rulesets/Base/mapreduce.jl
src/rulesets/LinearAlgebra/blas.jl
src/rulesets/LinearAlgebra/dense.jl
test/rulesets/Base/base.jl
test/rulesets/Base/broadcast.jl

See [ChainRulesCore](https://github.com/JuliaDiff/ChainRulesCore.jl/pull/129) for related PR

Update to new API

---

Project.toml
src/rulesets/Base/base.jl
src/rulesets/LinearAlgebra/dense.jl
src/rulesets/LinearAlgebra/structured.jl
test/rulesets/Base/base.jl
test/rulesets/LinearAlgebra/structured.jl

Found these because of Zygote's tests
while working on https://github.com/FluxML/Zygote.jl/pull/366
It is hard to add tests for them because they are about testing that
we didn't define a rule we should not have,
and that we don't thunk to many times

Fix errors revealed by Zygote's tests

---

Project.toml
test/rulesets/Base/array.jl
test/rulesets/Base/base.jl
test/rulesets/Base/mapreduce.jl
test/rulesets/LinearAlgebra/blas.jl
test/rulesets/LinearAlgebra/dense.jl
test/rulesets/LinearAlgebra/factorization.jl
test/rulesets/LinearAlgebra/structured.jl
test/rulesets/Statistics/statistics.jl

Resolves: #180 
From the Test [documentation](https://docs.julialang.org/en/v1/stdlib/Test/#Test.@testset) for `@testset`:
> Before the execution of the body of a @testset, there is an implicit call to Random.seed!(seed) where seed is the current seed of the global RNG.
So we do not need to manually seed our `@testsets`.

Use global random number generator

---

Project.toml
src/ChainRules.jl
src/rulesets/Base/base.jl
src/rulesets/Base/fastmath_able.jl
test/rulesets/Base/base.jl
test/rulesets/Base/fastmath_able.jl
test/runtests.jl

Closes #174 
(cc @mikeinnes)
Needs tests still.
The code has tests, in that it is still the same basic source as before, so the base cases are tested.
there are no tests of the fast math versions though.
Those tests can be generated in the same way however, if that is acceptable?
---
This PR also adds some missing tests for things that have fast math varients:
- `expm1`
- binary `+` and `-`, `/`, `\`, `max`, `min`
They are added in the trivial way, by adding them to the loops identical to others of their class.

Add rules for FastMath

---

src/rulesets/Base/base.jl

I think these should be ordinary zero, not `Zero()`, because they are often used in functions like `g(x) = x<0 ? zero(x) : x^2`, and this makes the gradient more likely to be type-stable. 
Edit: I see that github's editor has helpfully highlighted a lot of unicode for me, what's the policy here?

Rule for scalar zero(x) and one(x)

---

.travis.yml

Implements @oxinabox's suggestion in https://github.com/JuliaDiff/ChainRules.jl/issues/202. Also no longer allows failures on 1.3, but they shouldn't be necessary with this anyways.

Run Travis on latest stable release

---

Project.toml
src/rulesets/LinearAlgebra/structured.jl
test/rulesets/LinearAlgebra/structured.jl

This PR adds `rrule`s for `diagm`, specifically for the pair-based methods that are called by the other `diagm` methods.
It also adds the `rrule` for the general `diag` where the offset of the diagonal is provided.

Add more diag/diagm rrules

---

Project.toml
src/rulesets/LinearAlgebra/factorization.jl

closes #205 
the constraint on getting the primal right is not actually needed.

Remove constraints on primal from Composites for SVD and Cholesky

---

Project.toml
src/rulesets/LinearAlgebra/dense.jl
test/rulesets/LinearAlgebra/dense.jl

Adds rules for the cross product.
It includes a rule for chunked forward mode, following https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/37, where the chunked tangent vector matrices are assumed to have the size `(m, n)`, where `n` is the length of the input vectors and `m` is the number of chunks. Does this look right, @oxinabox @YingboMa?
Pending clarification on complex conjugation conventions ( https://github.com/JuliaDiff/ChainRulesCore.jl/issues/159) the `rrule` is restricted to real input vectors.

Rules for cross-product

---

src/rulesets/Base/fastmath_able.jl
test/rulesets/Base/fastmath_able.jl

The current rule for `sign(z::Complex)` is incorrect, as `sign(z::Complex) = z / abs(z)`. This PR adds rules for the complex `sign`. It also reimplements the rules for real inputs, to ensure that they do the right thing if passed complex (co)tangents (following https://github.com/JuliaDiff/ChainRules.jl/pull/196#discussion_r444566361).
The tests in this PR require #198 to pass.

Fix rules for sign with complex input

---

Project.toml
src/rulesets/LinearAlgebra/dense.jl
src/rulesets/LinearAlgebra/structured.jl
test/rulesets/Base/base.jl
test/rulesets/LinearAlgebra/dense.jl
test/rulesets/LinearAlgebra/structured.jl

As part of #210, PR adds missing complex tests and fixes where necessary for the array rules of the following functions, which lack type constraints:
- `dot`
- `det`
- `logdet`
- `Symmetric`
It does not release any type constraints. It also does not handle the BLAS rules (#214). This PR requires https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/47.

Fix complex array rules

---

Project.toml
src/ChainRules.jl
src/rulesets/Base/base.jl
src/rulesets/Base/fastmath_able.jl
src/rulesets/Base/utils.jl
test/rulesets/Base/base.jl
test/rulesets/Base/fastmath_able.jl

This PR fixes #215 by adding missing complex tests and where necessary generalizing rules and adding missing rules. New rules are
- `adjoint(::Number)`
- `real(::Number)`
- `imag(::Complex)`
- `Complex(::Number)`
- `Complex(::Number, ::Number)`
- `hypot(::Complex)`
- `hypot(::T, ::T) where T<:Union{Real,Complex}`
- `exp(::Number)`
It also simplifies the rules for `abs`, `angle`, and `sign` with shared utility functions.
I believe as of this PR, all scalar functions in Base for which we have complex rules should be tested on complex inputs.

Add missing complex tests and rules

---

src/rulesets/LinearAlgebra/blas.jl
test/rulesets/LinearAlgebra/blas.jl

As part of #210, this PR fixes #214 by adding missing complex tests for all rules for `BLAS` functions and fixing the rules where necessary. This should be the last piece of v0.7.0.
This PR uses the utility functions from #216, so it is blocked by that PR. Locally all tests pass.

Add complex tests and fix rules for BLAS functions

---

Project.toml

Following https://github.com/JuliaDiff/ChainRules.jl/issues/210, the rules that support complex inputs (and aren't as simple as summation or copying) now have complex tests. It should be safe to make a release. This PR removes the `DEV` tag from the version number.

Bump version number for release

---

Project.toml
src/rulesets/Base/base.jl
test/rulesets/Base/base.jl

~Most of the pushforward and pullback for `evalpoly` can be written as more calls to `evalpoly`, which is very efficient.~
Edit: This is true in the scalar case but not the matrix. In the current implementation, both the matrix and scalar polynomials have forward and reverse rules on the same order as `evalpoly` itself.
~Currently all but one of the tests fail for various reasons. I think the testers in ChainRulesTestUtils don't like when one of the inputs is a `Tuple`.~ Also, I don't expect the complex tests to pass until this package uses FiniteDifferences v0.10.0.
Edit: Oh, and I see that ChainRules doesn't test against 1.4 yet at all.
~@oxinabox I also tested against https://github.com/FluxML/Zygote.jl/pull/366 and may have hit a bug where Zygote doesn't like that the adjoint of `p` …

Add rules for evalpoly

---

Project.toml
src/rulesets/LinearAlgebra/dense.jl
src/rulesets/LinearAlgebra/utils.jl
test/rulesets/LinearAlgebra/dense.jl

This adds forward and reverse rules for `pinv` for the following inputs:
- `Number`
- `AbstractVector{T} where T<:Union{Real,Complex}`
- `Transpose{AbstractVector{T}} where T<:Union{Real,Complex}`
- `Adjoint{AbstractVector{T}} where T<:Union{Real,Complex}`
- `AbstractMatrix`
For the latter case, the `rrule` is equivalent to Zygote's `pinv` adjoint, but this is a little more efficient because it retracts over the largest dimension.

Add rules for pinv

---

Project.toml
src/ChainRules.jl
src/rulesets/Random/random.jl
test/rulesets/Random/random.jl
test/runtests.jl

Ideally this would be covered with a nograd macro along the lines of https://github.com/JuliaDiff/ChainRulesCore.jl/issues/150. Unfortunately I've not implemented that feature yet, so here we are.

MersenneTwister

---

Project.toml
src/rulesets/LinearAlgebra/structured.jl
src/rulesets/LinearAlgebra/utils.jl
test/rulesets/LinearAlgebra/structured.jl

Fixes #178 by porting the rules from Zygote, along with the `Hermitian` rules (see https://github.com/FluxML/Zygote.jl/blob/0b3e32d5c0f8e5ef3b061a6f84ed5505f5a202a0/src/lib/array.jl#L454-L491).
Tests currently do not pass I think because ChainRulesTestUtils seems to interpret the `:U` variable as a variable of name `U`, which does not exist. We may also need FiniteDifference v0.10.0 for the complex tests.

Add rules for all Symmetric/Hermitian constructors

---

Project.toml
src/rulesets/Random/random.jl

This PR (probably) fixes #227. `typeof(MersenneTwister)` is `DataType`, so the rules introduced in #223 will be applied to many function calls.
@baggepinnen can you confirm this resolves the issue for you?

Fix signature for MersenneTwister

---

src/rulesets/Random/random.jl

tiny style thing noticed in https://github.com/JuliaDiff/ChainRules.jl/pull/228 / https://github.com/JuliaDiff/ChainRules.jl/pull/223

Fixup naming convention `*_rrule` -> `*_pullback`

---

Project.toml
src/rulesets/Base/fastmath_able.jl
test/rulesets/Base/base.jl
test/rulesets/Base/fastmath_able.jl

This PR makes a few improvements to the rules for `^(::Number, ::Number)`.
For the general rule, it slightly improves the efficiency by removing the second `^` call.
It also adds a new real rule that avoids unnecessarily complexifying the tangents and cotangents. The general rule embeds the numbers in the complex plane for complex differentiation. However, for real negative base, exponentiation is undefined (literally throws an error) unless the exponent is exactly an integer. So for negative base, the derivative wrt the exponent is actually undefined (hence we can't even call FD on it). The new rule adopts the subgradient convention when the base is negative.
Oh, and since the rules are defined in `fastmath.jl`, I moved the test to the corresponding test file.
Here are are a few …

Improvements to numeric exponent rules

---

Project.toml
src/rulesets/Base/base.jl
src/rulesets/Base/fastmath_able.jl
test/rulesets/Base/fastmath_able.jl

Fix https://github.com/FluxML/Zygote.jl/issues/727. 
Still have to add tests. Where are `rrule_test`, `frule_test` and `scalar_test` defined? Do they check types?

fix division return type 

---

Project.toml
src/rulesets/Base/array.jl
src/rulesets/Base/mapreduce.jl
src/rulesets/LinearAlgebra/blas.jl
src/rulesets/LinearAlgebra/dense.jl
src/rulesets/LinearAlgebra/factorization.jl
src/rulesets/LinearAlgebra/structured.jl
src/rulesets/Statistics/statistics.jl

Following https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/53, this PR makes sure pullbacks do not thunk when they only return one non-`DoesNotExist` adjoint. It adds compatibility for ChainRulesTestUtils v0.5.0.

Don't thunk if only one adjoint exists

---

Project.toml
src/rulesets/Base/array.jl
test/rulesets/Base/array.jl

Code is basically the same as @AzamatB's https://github.com/FluxML/Zygote.jl/pull/501 (plus tests), but I think now it makes more sense to have this here.
This fixes `reduce(hcat, As)` and `reduce(vcat, As)` for Zygote, as otherwise you'd get the mutation error.

add adjoint for reduce hvcat

---

Project.toml
src/rulesets/LinearAlgebra/dense.jl
test/rulesets/LinearAlgebra/dense.jl

`det` and `logdet` were implemented for numbers but were untested. This PR adds number tests and removes the dangerous `inv` in their rules for number inputs. (see https://github.com/FluxML/Zygote.jl/issues/727#issuecomment-655361588).
It also adds rules for `logabsdet`.

Add logabsdet and test det and logdet on numbers

---

Project.toml
src/rulesets/LinearAlgebra/dense.jl

Fixing this makes e.g.`Zygote` "just work" with`MvNormal` and `GenericMvT` in `Distributions` by preventing `ChainRules` from taking control of the way that `AbstractPDMats` compute `logdet`.

Restrict types in logdet

---

Project.toml
src/rulesets/Base/fastmath_able.jl

@dpsanders pointed out that our scalar multiplication implementation returns thunks. As a policy we don't thunk scalar operations for simple operations as the tradeoff isn't typically worth it -- these appeared to creep through.
I'll add a separate don't-thunk-by-default test to `ChainRulesTestUtils` to make sure that this doesn't creep back in, but still lets rule-implementers use thunk if they _really_ want to.

Remove thunks on scalars

---

Project.toml
src/rulesets/Base/base.jl
test/rulesets/Base/base.jl

I recently became aware that Julia `Base` defines a `cosc` function to be the derivative of `sinc`, so it seems worth adding this rule (especially since naive differentiation of `sinc` leads to an implementation that is numerically unstable: https://github.com/JuliaLang/julia/issues/37227).

add Base.sinc rule

---

Project.toml
src/rulesets/Base/nondiff.jl

I don't really know what to call this, but it fixes https://github.com/JuliaDiff/ChainRules.jl/issues/257 , whatever that is.

Don't use non-differentiation  on any constructors

---

.github/workflows/IntegrationTestZygote.yml

Because Zygote's tests are broken in Juliia 1.5 (https://github.com/FluxML/Zygote.jl/issues/775)
we haven't had integration tests usable.
and #257  happened.
Our downstream Integration tests would have caught that.
cc @ChrisRackauckas

Pin the Integration Test for Zygote to Julia 1.4

---

Project.toml
src/rulesets/Base/array.jl
test/rulesets/Base/array.jl

Any time you test your rules without using finite differencing, you might as well not be testing your rules

Correct rrule for reshape

---

Project.toml
src/rulesets/LinearAlgebra/dense.jl
test/rulesets/LinearAlgebra/dense.jl

Nabla has this, we should have it too.
I am sure it can be extended to work for complex but i don't know how so am happy to make it a follow up PR

Add Array * Scalar

---

Project.toml
src/rulesets/LinearAlgebra/dense.jl
test/rulesets/LinearAlgebra/dense.jl

Needed for https://github.com/invenia/Nabla.jl/pull/189
I worked this one out with a white-board.
I'm not good at math though, but tests pass.
So I guess i got it right

Add scalar-array / and \

---

src/ChainRules.jl
src/rulesets/Base/arraymath.jl
src/rulesets/LinearAlgebra/dense.jl
src/rulesets/LinearAlgebra/structured.jl
test/rulesets/Base/arraymath.jl
test/rulesets/LinearAlgebra/dense.jl
test/rulesets/LinearAlgebra/structured.jl
test/runtests.jl

This has been grating on me for a while.
The rules for functions defined in `Base` belong in the `Base` folder.
But these had been handing in the `LinearAlgebra` folder.
This PR only moves the code.
No changes.
I am not bumping version because this doesn't need a release, its is invisible to the user

More Base's Array math into the Base ruleset folder

---

Project.toml
src/rulesets/LinearAlgebra/blas.jl
test/rulesets/LinearAlgebra/blas.jl

This is a simple typo.
Clearly we have no tests for this rule.
This is blocking for https://github.com/invenia/Nabla.jl/pull/189

fix typo in 4 arg gemm rrule

---

Project.toml
src/rulesets/Base/arraymath.jl
src/rulesets/LinearAlgebra/dense.jl
src/rulesets/LinearAlgebra/factorization.jl
src/rulesets/LinearAlgebra/utils.jl
test/rulesets/LinearAlgebra/factorization.jl

Follow up to https://github.com/JuliaDiff/ChainRulesCore.jl/pull/226
Needs that to be merged first

use add!! and rename _mulsubtrans!!

---

Project.toml
src/rulesets/LinearAlgebra/factorization.jl
src/rulesets/LinearAlgebra/structured.jl
test/rulesets/LinearAlgebra/factorization.jl

I am not 100% sure how i feel about this.
Maybe we should actually overload some more linear operators in ChainRulesCore.
Including in particular: the `Diagonal` constructor,
and `\` with a `Vector`
But for `svd_rev` because we use some of the inputs multiple times, it is actually faster to unthunk them at the start anyway.
I feel like we shouldn't actually have to use any input more than once, but that is another issue.
The testset in Nabla that revealed this was:
```julia
@testset "Tape updating from multiple components" begin
∇f = ∇() do X
U, S, V = svd(X)
Y = U * Diagonal(S) * V'
sum(Y)
end
X = [1.0 2.0; 3.0 4.0; 5.0 6.0]
@test ∇f(X)[1] ≈ ones(3, 2) atol=1e-5
end
```
I am not sure what is a good way to test this PR.
Do we want to add something to ChainRulesTestUtils that redoes all …

Adds some missing unthunks

---

Project.toml
src/rulesets/LinearAlgebra/blas.jl
test/rulesets/Base/base.jl
test/rulesets/Base/evalpoly.jl
test/rulesets/Base/fastmath_able.jl
test/rulesets/LinearAlgebra/blas.jl
test/rulesets/LinearAlgebra/factorization.jl
test/rulesets/packages/SpecialFunctions.jl
test/runtests.jl

closes #278 
This PR is the follow up from the integration tests failing in
https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/59
The core problem with the complex numbers was we were doing
`a = (b + a)' ` 
but we should have been doing
`a = b' + a`
but BLAS doesn;t have a shorthand for that
so what we actually do is:
`a = (b + a')'`
Other problem was us using some things were not differentials, and trying to acculate against them.
Requires
https://github.com/JuliaDiff/FiniteDifferences.jl/pull/111
for tests to pass, as needs to `to_vec` support for `AbstractZeros`
because its used in how ChainRulesTestUtil checks equality for `Composites`
which doesn't seem great, and seems like  in longer term to destructure the eqaulity checks is better
like in …

Correct inplace for complex BLAS and fix some accumulation against nondifferentails

---

Project.toml
src/rulesets/LinearAlgebra/factorization.jl
test/rulesets/LinearAlgebra/factorization.jl

This undoes most of https://github.com/JuliaDiff/ChainRules.jl/pull/282 as that is redundant with https://github.com/JuliaDiff/ChainRulesCore.jl/pull/121
but leaves the tests.
(other than fixing the assertions)
I am not bumping the version as this change should not be visable to the user.

stop manually unthunking composite

---

Project.toml
src/rulesets/LinearAlgebra/structured.jl
test/rulesets/LinearAlgebra/structured.jl

This is based on https://github.com/invenia/Nabla.jl/blob/4cadc87677fb1187354999dcf93bd528f45f85d0/src/sensitivities/linalg/triangular.jl
Differences:
- It generalizes it somewhat to apply `Diagonal` as well as `AbstractTriangular` matrixes
- It doesn't currently implement the inplace rules, because I am not sure they are worth it. 
- On the one hard it lets the `/` be fused with the accumulation, and avoids allocating the vector `s`
- On the other hand it it means carrying a reference to `X` rather than just a vector `s` of the same size as the diagonal of `x`
- @willtebbutt  what do you think? Should I add the inplace rules?

det and logdet for structured matrixes

---

src/rulesets/Base/fastmath_able.jl
test/rulesets/Base/fastmath_able.jl

close #100
tests don't fully pass because `fdm` doesn't work for all of them:
https://github.com/JuliaDiff/ChainRulesTestUtils.jl/blob/85739e41653de0e0026776116b62f2bcf2a7ba82/src/testers.jl#L94
```
julia> _fdm = ChainRulesTestUtils._fdm;
julia> ChainRulesTestUtils.jvp(_fdm, xs->ceil(xs...), (0.1, 1.0))
5.833333333333332
```
should we "manually test" it and/or use `complex_jacobian_test` (like for `abs`)?

add rules for round, floor, ceil

---

Project.toml
src/rulesets/Base/base.jl
src/rulesets/Base/fastmath_able.jl
test/rulesets/Base/base.jl
test/rulesets/Base/fastmath_able.jl

closes #294
Problem was that `round` etc was mistakenly put in `fastmathable.jl` even though there is no `Base.FastMath.round_fast`.
My fault for not spotting that during review.
This PR:
- move `round` etc and there tests to the right locations
- adds warning comments to the source antd tests about this
- adds some checks during the code generation to ensure every top-level statement in fastmath able is actually tranformed

Make sure to only fastmath the right things

---

Project.toml
src/rulesets/Base/base.jl
src/rulesets/Base/fastmath_able.jl

Fixes #291 
Currently tests fail though.

use `sincos` in rules for `sin` and `cos`

---

test/rulesets/LinearAlgebra/dense.jl
test/rulesets/LinearAlgebra/structured.jl

This is why we have been getting non-determinstic failures, even thouh the RNG seed was set.
`similar` just has whatever values was in RAM.
Which could well be NaN.
Turns out it was not FiniteDifferences.jl v0.11 at all.

Remove uses of similar to generate test inputs

---

.gitignore

fixes the mistakenly added submodule pointed out in https://github.com/JuliaDiff/ChainRules.jl/pull/304#issuecomment-728930890
adds `/dev` to gitignore to hopefully prevent it from happening again

Delete ChainRulesTestUtils submodule, and ignore

---

test/runtests.jl

The test on TravisCI have been timing out lately; due to lack of output.
I think it is because Travis is being super-slow.
but as we get more tests the possibility for it to go over 10 minutes without output increases.
We previously added `print(" ")` between testsets to stop this.
This PR goes further and just adds a print per `include`.
This is also nice for testing locally, as it gives a sense of progress.
Beyond this this PR also prints timing info so we can see which tests are taking longest.
And can catch them before any get to 10 minutes.
This is what the output looks like
```
Testing ChainRules.jl
Testing rulesets/Base/base.jl:   65.677611 seconds (149.48 M allocations: 7.257 GiB, 4.09% gc time)
Testing rulesets/Base/fastmath_able.jl:  81.614611 seconds (172.61 M allocations: …
```

Print what is being testing during tests and timing

---

.github/workflows/CI.yml
.github/workflows/JuliaNightly.yml
.github/workflows/Nightly.yml
README.md
test/rulesets/LinearAlgebra/dense.jl
test/rulesets/packages/SpecialFunctions.jl

This PR adds a GitHub Actions for CI. The goal is ultimately to replace Travis, though I recommend keeping both in parallel for a little while until we are sure we are happy with this.
cc @simeonschaub

Add GitHub Actions CI workflow

---

Project.toml
src/rulesets/LinearAlgebra/structured.jl
test/rulesets/LinearAlgebra/structured.jl

This PR pretty much brings us up to feature-parity with Zygote on the rules for `Adjoint` and `Transpose`.
TODO:
edit: the second and third points weren't achievable in this PR because our testing infrastructure isn't up to scratch at the minute. Opened [this issue](https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/80) regarding the problem.

Some Adjoint and Transpose stuff

---

Project.toml
src/rulesets/Base/array.jl
src/rulesets/Base/fastmath_able.jl
src/rulesets/Base/indexing.jl
src/rulesets/LinearAlgebra/blas.jl
src/rulesets/LinearAlgebra/norm.jl
src/rulesets/LinearAlgebra/structured.jl
src/rulesets/LinearAlgebra/symmetric.jl
src/rulesets/LinearAlgebra/utils.jl

This PR fixes most of the type-instabilities identified by https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/78, the remainder being documented in #328 and https://github.com/JuliaDiff/ChainRulesCore.jl/issues/265 or for type-unstable primals. I'm not yet adding any new tests because that would be redundant with the above PR. Until it is merged, this PR just checks that our current functionality tests still pass.

Fix various type-instabilities

---

Project.toml
src/rulesets/LinearAlgebra/factorization.jl
src/rulesets/LinearAlgebra/symmetric.jl

In https://github.com/FluxML/Zygote.jl/pull/875, I discovered that Zygote passes `Composite{Any}` types to our `rrule`s. #321 and #323 added rrules whose pullbacks were constrained to `Composite{<:Eigen}` and `Composite{<:SVD}`, which would cause Zygote to error. This PR changes those signatures to `::Composite`. It adds no new tests.

Change eigen and svd pullbacks to accept Composite{Any}

---

.github/workflows/CI.yml

These sets it up so an RSE at invenia will be notified if nightly build is broken.
So we w can fix it

Notificiations to Invenia slack on build fail

---

.github/workflows/VersionVigilante_pull_request.yml
Project.toml

Installs [this](https://github.com/bcbi/VersionVigilante.jl) wonderful GHA that @oxinabox pointed me towards.
Downsides:
1. It insists on a version bump for _every_ PR, regardless which bit of the code the PR touches.
Upsides:
1. It should substantially reduce the chance of forgetting to bump the patch -- it's annoying when this happens.
2. Will make it clearer to new contributors that we expect the version number to change when they contribute, over and above what is already discussed in ColPrac.
On balance I think this is a win, hence the PR. If we achieve consensus around this, I'll open PRs to the other ChainRules-related packages.

Install VersionVigilante

---

test/rulesets/LinearAlgebra/matfun.jl

The test suite for `exp` added in #331 accidentally only tested the real case. This PR fixes that. For some reason, the pushforwards and pullbacks are imprecise for `opnorm(A, 1) == 0.1` for real `A` for this seed. If I had to guess, it's because FiniteDifferences hits multiple branches in `exp`, and the branches have different precisions. I verified that we use the same coefficients for the Pade approximants that LinearAlgebra uses, and I verified that its coefficients are the exact same as those from the source code included with the corresponding paper. 🤷

Correctly test real matrix exponential

---

Project.toml
src/rulesets/LinearAlgebra/factorization.jl
test/rulesets/LinearAlgebra/factorization.jl

This PR adds rules for the LU decomposition of `StridedMatrix`es, as well as its use for computing the matrix inverse.
All rules are restricted to `StridedMatrix` inputs because these rules do not make efficient use of storage for inputs of type `SparseMatrixCSC` or `Tridiagonal`, each of which has their own specialized `lu` method.
EDIT: for a derivation of the rules, see https://sethaxen.com/blog/2021/02/differentiating-the-lu-decomposition/

Rules for LU decomposition of StridedMatrixes

---

test/rulesets/packages/SpecialFunctions.jl

part of https://github.com/JuliaDiff/ChainRules.jl/issues/360
Testign this is hard,
I had to manually add SpecialFunctions@0.10
because we need a version old enough to have `lgamma` and not the have `ChainRulesCore`.
CI will not do that and so the result will be meaningless
This code changes are pretty much just what is in 
https://github.com/JuliaMath/SpecialFunctions.jl/pull/300/files
but without `beta` stuff as  we don't define that apparently.

SpecialFunctions.jl autotangent

---

Project.toml
src/rulesets/Base/nondiff.jl

Ref https://github.com/JuliaLang/julia/pull/39132. I have also widened the signature here, since those correspond to the ones in Base. Not sure how to test this, I don't think there's a nice way to test the absence of method redefinition warnings when loading a module. Still requires https://github.com/JuliaDiff/ChainRulesCore.jl/pull/298.

stop redefining rules for `redirect_stdio` on 1.6

---

Project.toml
src/rulesets/LinearAlgebra/factorization.jl
src/rulesets/LinearAlgebra/symmetric.jl
test/rulesets/LinearAlgebra/symmetric.jl

improve inference in LinearAlgebra/symmetric

---

Project.toml
src/rulesets/LinearAlgebra/matfun.jl

Fixes #380 by ensuring that the cotangent used by the pullback of `exp` is mutable.
@Roger-luo can you confirm that this fixes the bug?

Ensure pullback of exp works for immutable arrays

---

Project.toml
src/ChainRules.jl
src/rulesets/LinearAlgebra/dense.jl
src/rulesets/LinearAlgebra/lapack.jl
test/rulesets/LinearAlgebra/dense.jl
test/rulesets/LinearAlgebra/lapack.jl
test/runtests.jl

This PR adds rules for the following functions:
- `frule` for `LAPACK.trsyl!` (solution to the Sylvester equation for (quasi)-triangular inputs)
- `frule`/`rrule` for `sylvester` (solution to the Sylvester equation)
- `frule`/`rrule` for `lyap` (solution to the Lyapunov equation)
All of the rules can be written in terms of the primal function itself. However, `sylvester` and `lyap` both use a Schur decomposition to solve an easier equation using `LAPACK.trsyl!`, so these rules then reuse that Schur decomposition. As a result, the included rule for `lyap` is much more efficient than the one in Zygote for `StridedMatrix` inputs.

Add rules for solutions to Sylvester and Lyapunov equations

---

Project.toml
src/rulesets/LinearAlgebra/factorization.jl
test/rulesets/LinearAlgebra/factorization.jl

Fix Composite of SVD

---

Project.toml
src/ChainRules.jl
src/rulesets/Base/sort.jl
test/rulesets/Base/sort.jl
test/runtests.jl

After #394  `sortperm` and `partialsortperm` rrule are in and Zygote can compute `sort` on its own, but not `partialsort`.
no speed gain for the `sort` rule in Zygote as of now but supporting thunks will make it faster in the future, or for AD systems which natively support ChainRules types.
Helps with #392

rrule for sort and partialsort

---

Project.toml
test/rulesets/Base/array.jl
test/rulesets/Base/base.jl
test/rulesets/Base/indexing.jl
test/rulesets/Base/mapreduce.jl
test/rulesets/Base/sort.jl
test/rulesets/LinearAlgebra/blas.jl
test/rulesets/LinearAlgebra/factorization.jl
test/rulesets/LinearAlgebra/lapack.jl
test/rulesets/LinearAlgebra/structured.jl
test/rulesets/LinearAlgebra/symmetric.jl

Depends on https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/129
For integers and symbols the explicit tangent is removed as `rand_tangent` returns `DoesNotExist()`

Update to using `DoesNotExist()` instead of `nothing` in tests

---

test/rulesets/Random/random.jl

These two tests implicitly assume that `NO_FIELDS` is a `ZeroTangent`. This PR removes this assumption to make way for https://github.com/JuliaDiff/ChainRulesCore.jl/pull/358

modify tests

---

Project.toml
src/rulesets/Base/mapreduce.jl
test/rulesets/Base/mapreduce.jl

This adds a reverse-mode gradient for `prod(x; dims)`, which should correctly treat zero entries. 
It ends up a little more complicated than seems ideal. In particular this won't work on CuArrays (at least when there are zeros, I think it will give a scalar access warning, which might be better than `NaN`s; when there aren't, it should work). Is there a mechanism worked out for where a Cu version of `∇prod_dims!` should live, if someone were to write one?
It also probably won't work well for second derivatives.

Add rule for `prod`

---

Project.toml
src/rulesets/Base/base.jl
src/rulesets/Base/fastmath_able.jl
src/rulesets/LinearAlgebra/symmetric.jl
src/rulesets/packages/NaNMath.jl

Going towards https://github.com/JuliaDiff/ChainRulesCore.jl/issues/354

Use true instead of One()

---

Project.toml
src/ChainRules.jl
src/rulesets/Base/array.jl
src/rulesets/Base/arraymath.jl
src/rulesets/Base/base.jl
src/rulesets/Base/evalpoly.jl
src/rulesets/Base/fastmath_able.jl
src/rulesets/Base/indexing.jl
src/rulesets/Base/mapreduce.jl
src/rulesets/Base/sort.jl
src/rulesets/LinearAlgebra/blas.jl
src/rulesets/LinearAlgebra/dense.jl
src/rulesets/LinearAlgebra/factorization.jl
src/rulesets/LinearAlgebra/matfun.jl
src/rulesets/LinearAlgebra/norm.jl
src/rulesets/LinearAlgebra/structured.jl
src/rulesets/LinearAlgebra/symmetric.jl
src/rulesets/Random/random.jl
src/rulesets/Statistics/statistics.jl
test/rulesets/Base/base.jl
test/rulesets/LinearAlgebra/factorization.jl
test/rulesets/LinearAlgebra/norm.jl
test/rulesets/LinearAlgebra/structured.jl
test/rulesets/LinearAlgebra/symmetric.jl
test/rulesets/Random/random.jl

Follow up to https://github.com/JuliaDiff/ChainRulesCore.jl/pull/358

Replace `NO_FIELDS` by `NoTangent()`

---

.github/workflows/Cancel.yml

I don't know anything about CI, so this might be very wrong - just testing it out

Cancel previous running workflows

---

.github/workflows/CI.yml
.github/workflows/JuliaNightly.yml

This package is pretty much OS agnostic.
I say we disable them until someone opens an issue saying something doesn't work on Windows etc.
A possibly alternative to this PR.
Would be to mix our matrix over the "diagonal".
So e.g.
- Julia 1.0, Mac, 64 bit
- Julia 1.0, Ubuntu, 32 bit
- Julia 1.x, Windows, 32 bit
gives use coverage of all OS and all julia version and all archetectures.
And maybe for bit more completeness:
- Julia 1.x, Ununtu, 64 bit
But writing GHA for that is a bit annoying, so could be a follow up PR

stop CI testing every  OS

---

Project.toml
src/ChainRules.jl
test/runtests.jl

Clean up after https://github.com/JuliaDiff/ChainRules.jl/pull/425, not sure what went wrong

remove `Requires` dependency and some `NaNMath`/`SpecialFunctions` artifacts

---

Project.toml
src/rulesets/LinearAlgebra/dense.jl
src/rulesets/LinearAlgebra/factorization.jl
test/rulesets/LinearAlgebra/dense.jl
test/rulesets/LinearAlgebra/factorization.jl

https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/168 (merged, and then reverted) introduced checks that the number of cotangents from the rrule is correct.
Possible fix for https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/168#issuecomment-854731827

Return the correct number of cotangents for functions with optional arguments

---

Project.toml
src/rulesets/LinearAlgebra/factorization.jl
test/rulesets/LinearAlgebra/factorization.jl

Ref https://github.com/JuliaLang/julia/pull/40623

fix lu deprecation warnings on Julia nightly

---

Project.toml
test/rulesets/LinearAlgebra/factorization.jl
test/rulesets/LinearAlgebra/matfun.jl
test/rulesets/LinearAlgebra/symmetric.jl

ref JuliaDiff/ChainRulesTestUtils.jl#165.
I will bump the version as well once #434 is merged so that PkgEval
picks this up.

use `@maybe_inferred` instead of `@inferred`

---

Project.toml
src/rulesets/Base/arraymath.jl
test/rulesets/Base/arraymath.jl

Fixes this:
```
julia> Zygote.gradient(x -> sum(abs, x / im), [1+im])
ERROR: StackOverflowError:
Stacktrace:
[1] map
@ ./tuple.jl:216 [inlined]
[2] _pullback(::Zygote.Context, ::typeof(Core._apply_iterate), ::typeof(iterate), ::Function, ::Tuple{typeof(/)}, ::Tuple{Vector{Complex{Int64}}, Complex{Bool}})
@ Zygote ~/.julia/dev/ZygoteRules/src/adjoint.jl:60
[3] _pullback
@ ./broadcast.jl:871 [inlined]
[4] _pullback(::Zygote.Context, ::typeof(Base.Broadcast.broadcast_preserving_zero_d), ::typeof(/), ::Vector{Complex{Int64}}, ::Complex{Bool})
@ Zygote ~/.julia/dev/Zygote/src/compiler/interface2.jl:0
```

Allow division by complex numbers

---

Project.toml
src/rulesets/Base/nondiff.jl

This allows Zygote to correctly differentiate things like
`rand!(similar(x))`. Since the output of `similar` does not have a
derivative with respect to the input arguments, this seems reasonable to
me.
fixes FluxML/Zygote.jl#997

add nondiff rule for `similar`

---

.gitignore
Project.toml
src/rulesets/Base/mapreduce.jl
test/rulesets/Base/mapreduce.jl
test/runtests.jl
test/test_helpers.jl

This is the real use of https://github.com/JuliaDiff/ChainRulesCore.jl/pull/363
needs tht to be merged first.
Soon I will make a Zygote PR that will to hit it.
Need to workout testing this

Rule for sum(f, xs)

---

Project.toml
src/rulesets/Base/array.jl
src/rulesets/Base/arraymath.jl
src/rulesets/Base/base.jl
src/rulesets/Base/evalpoly.jl
src/rulesets/Base/fastmath_able.jl
src/rulesets/Base/mapreduce.jl
src/rulesets/Base/sort.jl
src/rulesets/LinearAlgebra/blas.jl
src/rulesets/LinearAlgebra/dense.jl
src/rulesets/LinearAlgebra/factorization.jl
src/rulesets/LinearAlgebra/lapack.jl
src/rulesets/LinearAlgebra/matfun.jl
src/rulesets/LinearAlgebra/norm.jl
src/rulesets/LinearAlgebra/structured.jl
src/rulesets/LinearAlgebra/symmetric.jl
test/runtests.jl

Closes #408 
Needs https://github.com/JuliaDiff/ChainRulesCore.jl/pull/371
to do:
remove examples where the thunks can be unthunked more than once

Test accepting thunks

---

Project.toml
src/rulesets/Base/nondiff.jl

Fixes #344 
There are no tests for non_differentiable as discussed in https://github.com/JuliaDiff/ChainRules.jl/pull/252 . This *does* add a test here as it fits the criterion of either "add(ing) regression tests when we find issues with these rules / decide to add extra rules" but can just remove these tests if it's not wanted.

No Differentiable Factorial

---

Project.toml
src/rulesets/Base/array.jl
test/rulesets/Base/array.jl

Adds rrules for repeat. These are essentially copied from Zygote as suggested in #383 and hence taken from [here](https://github.com/FluxML/Zygote.jl/blob/956cbcf3c572c0eb09c146189bb38b1b434634ff/src/lib/array.jl#L130)
Doesn't include missing rules. At least from what I can tell, this is: 
```
function rrule(::typeof(repeat), xs::AbstractArray, counts::Integer...)
```
One change from the original code in Zygote:  closes instead of the value of the size of `xs` rather than `xs` itself. Also adds an `unthunk`. 
Note, I saw #405 after looking at this (that caught the above), but not sure if that is being actively worked on.

Add repeat rules from Zygote

---

Project.toml
src/rulesets/Base/arraymath.jl
src/rulesets/Base/base.jl
src/rulesets/Base/nondiff.jl
test/rulesets/Base/arraymath.jl
test/rulesets/Base/base.jl

Fixes dfdx/Yota.jl#92
This PR doesn't contain `frule` for the same operation, but most other functions in `arraymath.jl` don't have either. Is it normal practice to add only one kind of rules? I don't know much about forward-mode AD ecosystem so it's a bit hard for me to estimate the impact.

Add rrule for multiarg array addition

---

Project.toml
src/rulesets/Base/arraymath.jl
test/rulesets/Base/arraymath.jl

@AlexRobson this should fix your thing.
We basically need to be pretty careful not to use InplaceableThunks when we don't know that sensible things will be happening for the input.
So this PR basically just removed buggy code, and adds back a special-case that is known not buggy.
A downside is that some places were we could inplace we don't anymore. e.g. `*(::Diagonal, ::Diagonal)`
and `*::(StridedVector, StridedMatrix)`. Could add those back if we really wanted.
But since noone is really using the InplaceableThunk in anger, just holding off on that for now.
solving it generally is https://github.com/JuliaDiff/ChainRulesCore.jl/issues/411
I recommend Turning off showing whitespace when reveiwing

don't try an Inplace unknown matrixes in *

---

Project.toml
src/rulesets/Random/random.jl
test/rulesets/Random/random.jl

In general it is pretty much nonsense to be doing AD through the constructor of any random number generator.
Not just a `MersenneTwister`.
Julia introduces a new default RNG in 1.7
can we use `@nondifferentiable` for this now?
Probably wants tests.
Hopefully fixed https://github.com/SciML/DiffEqSensitivity.jl/runs/3191036433?check_suite_focus=true#step:6:272

Make construtors of all AbstractRNGs as nondifferentiable

---

Project.toml
src/rulesets/Base/base.jl
src/rulesets/Core/core.jl
test/rulesets/Base/base.jl
test/test_helpers.jl

The ProjectTo constructors use a few functions/builtins
that did not previously have rules breaking higher order
AD, since these constructors are now called by the first
order rules.

Add a few rules needed for higher-order AD of ProjectTo

---

Project.toml
src/rulesets/Base/mapreduce.jl
src/rulesets/Base/nondiff.jl
test/rulesets/Base/mapreduce.jl

Replaces #493 . Moves the same logic as before to a new (internal) function, for which additional rules are defined, to allow for higher-order derivatives. And inserts a few `Ref` to make this work for arrays of arrays.

Rule for `sum` allowing 2nd derivatives

---

Project.toml
src/rulesets/Base/fastmath_able.jl
test/rulesets/Base/fastmath_able.jl

Hello,
as discussed on [discourse](https://discourse.julialang.org/t/automatic-differentiation-of-cispi/66075), differentiation of `cispi` fails, which is due to `copysign` being non differentiable. This problem is avoided by defining a rule for `sincospi` in `fastmath_able.jl`. Note the the sign was moved from `\pi` to the sine term (`sinpix`), to warrant that `\pi` does not enforce Float64 as result type, which `-\pi` would do.
Hope that the edit is acceptable, but happy to adapt, if needed.

Add rule for `sincospi`

---

Development/Project.toml
Project.toml
src/rulesets/Base/fastmath_able.jl
test/rulesets/Base/fastmath_able.jl

As opposed to the previous [discussion](https://github.com/JuliaDiff/ChainRules.jl/issues/498) the correct rule for `copysign(y,x)` should probably be:
```julia
@scalar_rule copysign(y, x) (ifelse(signbit(x)!=signbit(y), -one(y), +one(y)), NoTangent())
```
. You can also find the arguments there why `NoTangent()` is preferred over `0`. 
The testing gets into problems, if too close to zero for x or y, due to the non-continuity of this function.

new rule: copysign

---

.github/workflows/CI.yml
Project.toml
README.md
test/rulesets/Base/fastmath_able.jl
test/runtests.jl

Turns out we can use JuliaInterpreter to shave another good 30% off test times. It does mean taking on another test-only dependency, but I think that's worth it.

use JuliaInterpreter for even faster tests 

---

Project.toml
src/rulesets/Base/base.jl
src/rulesets/Base/fastmath_able.jl
test/rulesets/Base/base.jl
test/rulesets/Base/fastmath_able.jl

These slipped in #502 and  #497.
Bad reviewing on my part.
I trusted the system we had in-place to catch anything that was in the wrong place.
However it is tricked if the function is not fast mathable, but a function it calls is.
It may be worth investing in a better check.
Or working out a way error if we break precompilation
This should I think fix https://github.com/invenia/Nabla.jl/issues/208

copysign and sincospi are not fastmath-able

---

Project.toml
src/rulesets/Base/array.jl
test/rulesets/Base/array.jl

Follow up from #460 
Adds in the missing `function rrule(::typeof(repeat), xs::AbstractArray, counts::Integer...)` method. 
Uses the code provided by @mcabbott in the gist [here](https://gist.github.com/mcabbott/80ac43cca3bee8f57809155a5240519f)
Some comments:
- ~There were some type infererence issues in running in 1.0 IDK how important this is is (a bunch of stuff is marked to only check inference in later versions), but to avoid regressing on the tests already implemented I've added some type hinting in the closure. It's a bit gross so there may be a better way to do it.~ EDIT: Now removed and just relaxing the 1.0 tests for typing. 
- ~Bumps finite differences so `rand_tangent{Array{T, 0}}` is now doing the correct thing and hence enables those tests. There are some differences in the …

Add missing generic repeat method

---

Project.toml
src/rulesets/Base/nondiff.jl

Based on @oxinabox 's reply here: https://github.com/SciML/DiffEqFlux.jl/issues/502#issuecomment-902023817 .
This solves also the issues with the callback construction in https://github.com/SciML/DiffEqFlux.jl/issues/502.
Does it need a test? Should I maybe add one from https://github.com/SciML/DiffEqFlux.jl/issues/502#issuecomment-902015247 in here: https://github.com/JuliaDiff/ChainRules.jl/blob/master/test/rulesets/Base/array.jl ?

do not differentiate through the construction of BitArray

---

Project.toml
src/rulesets/LinearAlgebra/structured.jl
test/rulesets/LinearAlgebra/structured.jl

Adding an `rrule` for `sqrt(::Diagonal)`, relating to [a comment](https://github.com/JuliaDiff/ChainRulesCore.jl/issues/441#issuecomment-902941440) in an issue discussing structural vs natural `Tangents`

Add rules for sqrt(::Diagonal)

---

Project.toml
src/rulesets/Base/array.jl
test/rulesets/Base/array.jl

Closes #518 
ProjectTo in these rearranging linear operators seems not worth it.
It causes problems since they are often used on types that are on representing vector spaces -- and ProjectTo is not fully defined on those.
Which then error.
See #518 for more details.
These are fine if we were given good pullback inputs (i.e. if the functions called after did ensure things were good), we preserve those.
(circshift doesn't work on (any?) structurally spaces matrixes anyway)

Don't ProjectTo in reverse or circshift

---

Project.toml
src/rulesets/Base/base.jl
src/rulesets/Base/fastmath_able.jl
test/rulesets/Base/base.jl
test/rulesets/Base/fastmath_able.jl

Builds on #485 but tries to get all the edge cases. Still a bit messy.

Fix rules for `^`

---

Project.toml
src/rulesets/Base/mapreduce.jl
test/rulesets/Base/mapreduce.jl

closes #522 
This will still error if `f` in `sum(f, xs)` is a non-callable struct, but we can cross that bridge once (if ever) we actually get to it.

`@opt_out of sum(array, array)`

---

Project.toml
src/rulesets/Base/array.jl
src/rulesets/Base/indexing.jl
src/rulesets/Random/random.jl

Minor tweak to do things like `map(Returns(ZeroTangent()), args)` instead of having a separate anonymous function each time.

Use `Returns`

---

src/rulesets/Base/mapreduce.jl
test/rulesets/Base/mapreduce.jl
test/test_helpers.jl

Closes https://github.com/FluxML/Zygote.jl/issues/1074
Basically when there is not a `dims` argument given, we need to do a "left-hand" broadcast.
where `call.(pullback, ȳ)` broadcasts `ȳ` up to the shape of `pullback`
but when `dims` is given then we need to do a "outer" broadcast that broadcasts using shape info from both `pullback` and `ȳ`

Handle sum(f,xs) where f returns a Vector

---

Project.toml
src/rulesets/Base/mapreduce.jl
test/rulesets/Base/mapreduce.jl
test/test_helpers.jl

This is a backport of #534  to the release-0.8 branch.
Thus closing https://github.com/FluxML/Zygote.jl/issues/1074
which required it to work in Zygote v0.6.13
As this is just a backport and #534 has already been reviewed this does not require review

Backport: handle sum(f, xs) where f returns a Vector

---

src/rulesets/Base/sort.jl
test/rulesets/Base/sort.jl

Rules for `sortslices`, `unique`

---

Project.toml
src/rulesets/Base/fastmath_able.jl
test/rulesets/Base/base.jl
test/rulesets/Base/fastmath_able.jl

Closes #544
This makes an `rrule` for 3, and one for many arguments which peels off 3. It's possible that 2 and many would be as good, I don't think I tried that.
Also adds a trivial rule for unary `*` although I'm not sure it's necessary.

`rrule` for many-arg `*`

---

test/rulesets/LinearAlgebra/structured.jl
test/rulesets/LinearAlgebra/symmetric.jl

Closes #549 
- Change in structured handles factorization becoming less accurate and thus finite differencing beween less accurate
-  Just ups out tolerance of error
- https://github.com/JuliaDiff/ChainRules.jl/runs/4390009367?check_suite_focus=true#step:6:134
And
- Change in symmetric handles factorization becoming less accurate and thus the finite differencing escaping the domain (we possibly should fix the `_fdm` to point the right way though?)
- This change just makes sure our initial point is less close to boundry

fix for julia 1.7

---

Project.toml
src/rulesets/Base/base.jl

This PR replaces handcoded conversions from degrees to radians and radians to degress with `deg2rad` and `rad2deg`.
Arguably this simplifies the code and allows to use specializations in e.g. Base (https://github.com/JuliaLang/julia/blob/cbc2ce819662648da90366334e5c6bf1da1c4717/base/math.jl#L306-L336).

Use `deg2rad` and `rad2deg` instead of handcoding conversions

---

src/rulesets/Base/array.jl
test/rulesets/Base/array.jl

Rule for `permutedims`

---

Project.toml
src/rulesets/Base/arraymath.jl
test/rulesets/Base/arraymath.jl

https://github.com/JuliaLang/julia/pull/37898 adds some 3- and 4-arg methods to `*`, do to things like contract matrices in the optimal order. That eventually calls pairwise `*` so shouldn't break AD.
It also fuses scalar-matrix-matrix multiplication, which involves calling `mul!`, and thus I think will break things. So this adds some rules!
The RFC is about exactly which functions to attach rules to, and with what signatures. The basic function is `mat_vec_scalar(A, x, γ) = A * (x .* γ)`, but this has some methods which call `_mat_vec_scalar` which actually does the mutation. The minimal thing would be to attach the rule to `_mat_vec_scalar`, but it might be more efficient to call the fused rule in some other cases, rather than leaving AD to sort out the broadcast etc. (It's also not too …

RFC: rules related to 3-arg `*`

---

Project.toml
src/rulesets/Base/evalpoly.jl

As noted in https://github.com/JuliaDiff/ChainRules.jl/pull/564#issuecomment-1015540993, `evalpoly` in base only has the following methods:
```julia
[1] evalpoly(z::Complex, p::Tuple{Any}) in Base.Math at math.jl:201
[2] evalpoly(z::Complex, p::Tuple) in Base.Math at math.jl:176
[3] evalpoly(x, p::Tuple) in Base.Math at math.jl:152
[4] evalpoly(z::Complex, p::AbstractVector) in Base.Math at math.jl:204
[5] evalpoly(x, p::AbstractVector) in Base.Math at math.jl:165
```
This PR limits our `evalpoly` definition to only cover these signatures. This fixes #533.

Limit evalpoly rule signatures to those in Base

---

Project.toml
src/ChainRules.jl
src/rulesets/LinearAlgebra/uniformscaling.jl
test/rulesets/LinearAlgebra/uniformscaling.jl
test/runtests.jl

These were at first made a Tangent because:
```
julia> gradient(x -> sum([1 2; 3 4] * x), I*3.14)
(Tangent{UniformScaling{Float64}}(λ = Thunk(ChainRules.var"#1360#1364"{Matrix{Float64}, Matrix{Int64}, ProjectTo{Float64, NamedTuple{(), Tuple{}}}}([1.0 1.0; 1.0 1.0], [1 2; 3 4], ProjectTo{Float64}())),),)
```
But perhaps `I` in fact represents its own gradient Done in  https://github.com/JuliaDiff/ChainRulesCore.jl/pull/533

Some rules for `UniformScaling`

---

Project.toml
src/rulesets/LinearAlgebra/matfun.jl
test/rulesets/LinearAlgebra/matfun.jl

Fixes #512.
I'm not certain how to test this, since I was unable to replicate in ChainRules the bug observed in Zygote in that issue, but with the fix here, we get
```julia
julia> using Zygote
julia> gradient(x -> sum(abs, exp(x)' + exp(x)'), [1 2; 3 4.0])
([226.54923657197995 427.40643795569565; 309.84981350932094 579.219109950626],)
julia> gradient(x -> sum(abs, 2 * exp(x)'), [1 2; 3 4.0])
([226.54923657197995 427.40643795569565; 309.84981350932094 579.219109950626],)
```

Don't mutate cotangent in rule for `exp`

---

Project.toml
src/rulesets/Base/nondiff.jl

This PR marks the Bool-valued `Base.allunique` as non-differentiable.

Mark allunique non_differentiable

---

Project.toml
src/rulesets/LinearAlgebra/dense.jl
test/rulesets/LinearAlgebra/dense.jl

Fix `rrule` for  complex-valued determinants

---

Project.toml
src/rulesets/Base/array.jl
test/rulesets/Base/array.jl

Currently, https://github.com/JuliaDiff/ChainRules.jl/blob/8c34f19d3a8a8a224c9fbe20524d2a08c8b9bf81/src/rulesets/Base/array.jl#L356-L362 will generate a `Tuple{Union{UnitRange{Int64}, Colon}, ...}`. When the number of input dims >=3, this appears to fail some union-splitting threshold for `getindex` on certain array types. Here's a MWE with FillArrays, which Zygote uses somewhat extensively:
```julia
using Test, ChainRules, ChainRulesCore, FillArrays
function grad(x1, x2, sens, dims::Val)
y, back = rrule(cat, x1, x2; dims)
back(sens)
end
@inferred grad(ones(1, 1, 1), ones(1, 1, 1), ones(1, 2, 1), Val(2))
@inferred grad(Ones(1, 1), Ones(1, 1), ones(1, 2), Val(2))
@inferred grad(Ones(1, 1, 1), Ones(1, 1, 1), Ones(1, 2, 1), Val(2))
@inferred grad(ones(1, 1, 1), ones(1, 1, 1), Ones(1, 2, 1), …
```

Improve type stability of `cat_pullback`

---

Project.toml
src/rulesets/LinearAlgebra/norm.jl

Was staring at code and noticed this

Eliminate redundant call to `norm`

---

src/rulesets/Base/mapreduce.jl
src/rulesets/Statistics/statistics.jl
test/rulesets/Statistics/statistics.jl
test/test_helpers.jl

Closes #85, closes https://github.com/FluxML/Zygote.jl/issues/1128 
Builds on #529, similar performance:
```julia
julia> using Statistics
julia> @btime gradient(x -> mean(abs, x), $(rand(30,30)));
30.583 μs (108 allocations: 152.05 KiB)  # before
2.056 μs (17 allocations: 7.73 KiB)      # after -- uses derivatives_given_output
julia> @btime gradient(x -> sum(mean(log, x, dims=1)), $(rand(30,30)));  # was an error
9.583 μs (18 allocations: 8.11 KiB)  # after -- uses derivatives_given_output
julia> @btime gradient(x -> mean(log∘exp, x), $(rand(300,300))); 
1.035 s (6930185 allocations: 198.45 MiB)     # before
825.696 ms (5940068 allocations: 142.83 MiB)  # after -- stores Zygote pullbacks, unstable
julia> @btime mean((log∘exp).(x)) setup=(x=$(rand(300,300)));
1.578 ms (2 allocations: …
```

Rule for `mean(f,x)`

---

Project.toml
src/rulesets/Statistics/statistics.jl
test/rulesets/Statistics/statistics.jl
test/test_helpers.jl

Reverts JuliaDiff/ChainRules.jl#615
because 
This broke Invenia's code base. Something went wrong with how this works with NamedDims.jl.
I am reverting this til it can be debugged
```
2022-05-17T18:24:11Z	MethodError: no method matching iterate(::Nothing)
2022-05-17T18:24:11Z	Stacktrace:
2022-05-17T18:24:11Z	  [1] indexed_iterate(I::Nothing, i::Int64)
2022-05-17T18:24:11Z	    @ Base ./tuple.jl:89
2022-05-17T18:24:11Z	  [2] rrule(config::Zygote.ZygoteRuleConfig{Zygote.Context}, ::typeof(Statistics.mean), f::NamedDims.NamedDimsArray{(:target, :node), Float32, 2, Matrix{Float32}}, x::StatsBase.AnalyticWeights{Float32, Float32, Vector{Float32}}; dims::Function)
2022-05-17T18:24:11Z	    @ ChainRules ~/.julia/packages/ChainRules/OJ3vT/src/rulesets/Statistics/statistics.jl:26 …
```

Revert "Rule for `mean(f,x)`"

---

src/rulesets/Base/arraymath.jl

Fix the specialized `rrule` for `StridedArray` multiplication to equal `eltype`. Fixes issue [#625](https://github.com/JuliaDiff/ChainRules.jl/issues/625).

restrict strided array multiplication `rrule`

---

Project.toml
src/rulesets/Base/indexing.jl

This fixes an error found in downstream tests when removing Zygote's rule, https://github.com/FluxML/Zygote.jl/pull/1253 
I did think this was supposed to be handled upstream?
Before:
```julia
julia> rrule(eachcol, [1 2; 3 4])  # looks OK
(SubArray{Int64, 1, Matrix{Int64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}[[1, 3], [2, 4]], ChainRules.var"#allcols#1468"{Matrix{Int64}}([1 2; 3 4]))
julia> rrule(eachcol, [1 2; 3 4])[2](ZeroTangent())  # produces the error seen in 1253
ERROR: MethodError: no method matching keys(::ZeroTangent)
Closest candidates are:
keys(::Tuple)
@ Base tuple.jl:71
keys(::Tuple, ::Tuple...)
@ Base tuple.jl:76
keys(::IOContext)
@ Base show.jl:397
...
Stacktrace:
[1] pairs(collection::ZeroTangent)
@ Base ./abstractdict.jl:172
[2] …
```

make ∇eachslice accept AbstractZero

---

Project.toml
src/ChainRules.jl
src/rulesets/Base/nondiff.jl
src/rulesets/Distributed/nondiff.jl
src/rulesets/LinearAlgebra/nondiff.jl

Closes #635 
Also removes `floor`, `ceil`, and `round` non-diff from [previous PR](#636). I overlooked that we already have
```julia
@scalar_rule round(x) zero(x)
@scalar_rule floor(x) zero(x)
@scalar_rule ceil(x) zero(x)
```
which looks like there is a reason we don't use `@non_differentiable`, though it isn't clear to me why.

add remaining `@nograd` from Zygote

---

Project.toml
src/rulesets/Base/base.jl
src/rulesets/Base/mapreduce.jl
test/rulesets/Base/base.jl
test/rulesets/Base/mapreduce.jl

I wrote this some time ago, but playing with Yota today, it came up as a missing rule. Diffractor also fails to differentiate this without the rule:
```julia
julia> Yota.grad(x -> map(*, x, (4,5,6), (7,8,9))[2], (2,3,4))  # with PR
(120, (ZeroTangent(), Tangent{Tuple{Int64, Int64, Int64}}(ZeroTangent(), 40.0, ZeroTangent())))
julia> Diffractor.gradient(x -> map(*, x, (4,5,6), (7,8,9))[2], (2,3,4))  # with PR
(Tangent{Tuple{Int64, Int64, Int64}}(ZeroTangent(), 40.0, ZeroTangent()),)
```
This is simpler than `map` for arrays, and judging by how `foldl` went, it's probably better to treat them separately. 
* This reverses the iteration, since `map` on tuples is unrolled, and maybe people rely on it working in order. 
* ~~It allows mismatched lengths,~~ like `zip`, although Base currently …

Rule for `map(f, ::Tuple...)`

---

Project.toml
src/rulesets/Base/indexing.jl

Correction to https://github.com/JuliaDiff/ChainRules.jl/pull/643 to avoid this:
```
julia> frule((NoTangent(), NoTangent()), Base.tail, (3,4))
ERROR: MethodError: no method matching length(::NoTangent)
Closest candidates are:
length(::Union{Base.KeySet, Base.ValueIterator})
@ Base abstractdict.jl:58
length(::Union{NNlib.BatchedAdjoint{T, S}, NNlib.BatchedTranspose{T, S}} where {T, S})
@ NNlib ~/.julia/packages/NNlib/uDZz6/src/batched/batchedadjtrans.jl:58
length(::Union{DataStructures.OrderedRobinDict, DataStructures.RobinDict})
@ DataStructures ~/.julia/packages/DataStructures/59MD0/src/ordered_robin_dict.jl:86
...
Stacktrace:
[1] _similar_shape(itr::NoTangent, #unused#::Base.HasLength)
@ Base ./array.jl:660
[2] _collect(cont::UnitRange{Int64}, itr::NoTangent, #unused#::Base.HasEltype, …
```

Simplify `frule` for `Base.tail`

---

Project.toml
src/rulesets/Statistics/statistics.jl

Closes #652 
Should we add test-only NamedDims dependency to test this?

fix `rrule` for `mean` bug

---

Project.toml
test/rulesets/Base/array.jl
test/rulesets/Base/arraymath.jl
test/rulesets/Base/mapreduce.jl
test/rulesets/LinearAlgebra/dense.jl
test/rulesets/LinearAlgebra/norm.jl
test/rulesets/Statistics/statistics.jl
test/test_helpers.jl

This wants to start adding GPU tests...
* This uses the fake `JLArray` from https://github.com/JuliaRegistries/General/pull/64443 so that this can run on github actions / random laptops.
* Adding `@gpu` in front of `test_rrule(sum, rand(3))` expands to first run the test as before, then check the GPU result. No attempt is made to run all the tests this way.
Xref #617 -- note that there is now GPUArraysCore.jl, so CR can use `@allowscalar`, and dispatch on `AbstractGPUArray`, without loading anything heavy.
Xref #645 -- that particular rule needs to be re-written, marked broken here.

RFC: add GPU testing

---

Project.toml
src/rulesets/LinearAlgebra/factorization.jl
test/rulesets/LinearAlgebra/factorization.jl

`\(::Cholesky, ::AbstractVecOrMat)` and `/(::AbstractMatrix, ::Cholesky)` internally call `ldiv!` and `rdiv!`, respectively. This PR adds `rrule`s for these functions to cover this up. This also allows the correspond adjoint for `\` to be removed from Zygote.
Fixes #611

Add rules for division by Cholesky

---

Project.toml
src/rulesets/LinearAlgebra/factorization.jl
test/rulesets/LinearAlgebra/factorization.jl

Fixes #477 by adopting a similar approach as #434, except that it uses a type union to still support the old syntax. This will need to be removed for future Julia versions when the deprecated syntax is removed.

Use new cholesky pivot syntax in v1.8

---

Project.toml
src/rulesets/Base/array.jl
src/rulesets/Base/indexing.jl

This has been deprecated. I think it would be helpful to users to test with `--depwarn=error` but I'm not sure how to enable that when using `julia-runtest`. @DilumAluthge Do you know if that is possible?

Don't use UnionAlls in Varargs

---

src/rulesets/Base/array.jl

Fixes, e.g, the example below:
```julia
using Unitful, UnitfulChainRules
using Zygote
Zygote.gradient(A -> ustrip.(maximum(A)), [1.0, 2.0, 3.0] * u"m")
```
This occurs because we hardcode the `0` in `_zerolike_writeat`, which ends up getting called through the `maximum` `rrule`, among others. Using `zero(eltype(dy))` we can fill with the proper `0`-like. 
I included a check just in case `eltype(dy) == Any`, in which case we default to the previous behavior as `zero(Any)` is undefined. 
Is there a better way to determine when `zero(eltype(dy))` wouldn't be valid? Maybe defaulting to `ZeroTangent()` would be better in the case where `eltype` doesn't concretely define a `zero`?

Use `eltype` to determine the proper zero to `fill!` in _zerolike_writeat

---

Project.toml
src/rulesets/Base/broadcast.jl
test/rulesets/Base/broadcast.jl

Remove `NTuple` from `unbroadcast`

---

Project.toml
src/rulesets/Base/arraymath.jl
src/rulesets/Base/broadcast.jl

The `rrule` for `+` would silently unthunk N times, by calling `reshape`. (Maybe `test_rrule` should have a thunk which counts to test for such mistakes?)
And most broadcasting would fail on thunks, by calling something like `ndims(@thunk [1,2])`. (Not sure why this didn't cause failures.)

Explicitly `unthunk` in a few rules

---

Project.toml
src/rulesets/Base/broadcast.jl
src/rulesets/Base/nondiff.jl
test/rulesets/Base/broadcast.jl

Companion to https://github.com/JuliaDiff/Diffractor.jl/pull/89

Minor broadcasting fixes

---

Project.toml
src/rulesets/Base/indexing.jl
src/rulesets/Base/nondiff.jl
src/rulesets/Statistics/statistics.jl

Fixes this:
```julia
julia> Zygote.hessian_reverse(x -> sum(sin, mean(x.^2; dims=1)), [1 2; 3 4.0])  # Int
4×4 Matrix{Float64}:
1.24259  2.87677  0.0      0.0
2.87677  8.91398  0.0      0.0
0.0      0.0      1.33701  4.35217
0.0      0.0      4.35217  7.86527
julia> Zygote.hessian_reverse(x -> sum(sin, mean(x.^2; dims=[1])), [1 2; 3 4.0])  # Vector
4×4 Matrix{Float64}:
1.24259  2.87677  0.0      0.0
2.87677  8.91398  0.0      0.0
0.0      0.0      1.33701  4.35217
0.0      0.0      4.35217  7.86527
julia> Zygote.hessian_reverse(x -> sum(sin, mean(x.^2; dims=(1,))), [1 2; 3 4.0])  # Tuple
ERROR: Mutating arrays is not supported -- called push!(Vector{Int64}, ...)
...
Stacktrace:
...
[5] unique
@ ./set.jl:176 [inlined]
[6] (::typeof(∂(unique)))(Δ::Nothing)
@ Zygote …
```

`@non_differentiable _denom`

---

src/rulesets/Base/nondiff.jl

This is intended to fix https://github.com/FluxML/Zygote.jl/issues/1372

Added differentiation rule for `promote_type`

---

test/rulesets/Base/array.jl

As noted in https://github.com/JuliaDiff/ChainRules.jl/pull/691 these now pass.
I don't know why, but its good
This does not need a version bump as it isn't changing package behavour

remove broken marking on max/min-imum gpu tests

---

Project.toml
src/rulesets/Base/broadcast.jl
test/rulesets/Base/broadcast.jl

Fixes JuliaDiff/ChainRules.jl#708.
Maybe this closes JuliaDiff/ChainRulesCore.jl#618 too -- it narrows the cases for which it uses `frule_via_ad` to those with one real number; perhaps you could allow structs containing one real number, but anything worse won't work. 
Failure on 32-bit systems doesn't seem related, also happened before?  https://github.com/JuliaDiff/ChainRules.jl/actions/runs/4654246289/jobs/8235815448

Some broadcasting fixes

---

src/rulesets/Base/arraymath.jl
test/rulesets/Base/arraymath.jl

https://github.com/JuliaLang/julia/pull/44358 broke our things on julia 1.9
this gets it back, but idk numerical linear algrebra so I am not sure it doesn't cost us anything.
Also inv is broken on GPU again.

Fix for julia 1.9

---

src/rulesets/Base/fastmath_able.jl

While it would be best to fix `Base.rest()` to be able to infer properly, at the moment the destructuring with a splat in the arguments to this `frule` end up causing inference issues in Diffractor.

Avoid lowering to `Base.rest()`, as it infers poorly

---

Project.toml
src/rulesets/Base/indexing.jl
test/rulesets/Base/array.jl
test/rulesets/Base/indexing.jl

I think this is maybe is a precondition for https://github.com/FluxML/Zygote.jl/pull/1328
so that we know that deleting the Zygote rules will not cause performance regressions.
Still WIP as i chase down failing tests.

Bring over OneElement for scalar getindex

---

src/rulesets/Base/arraymath.jl

Pointed out by @Marius311
not sure how this happened.
I blame Linux/X's  middle-click paste.
This code was unused, looks like it was part of a draft for rewriting `/` but it wasn't completed (no use of `add!!`)
So we can just delete it.
@marius311 if you want to give this a look and give it an approve, I can merge this

Remove odd overload of calling array on an array

---

src/rulesets/Base/indexing.jl
test/rulesets/Base/indexing.jl

Having this chain rule is sub-optimal, because it prevents early-SROA in Diffractor-like systems that would like to perform some optimizations before applying AD (but can't do any optimization on functions that have custom rules). By letting it go down to the `getfield`, regular SROA can apply. Any AD system should handle `getfield` anyway, so I don't think there's a strong reason to have this.
Similar reasoning applies to the reverse rules also, but they aren't currently actively causing me problems, so this PR only removes the frule, since I don't think many other packages are using them. We can revisit the rrules later.

Remove frule for getindex(::Tuple, i)

---

Project.toml
src/rulesets/Base/arraymath.jl
test/rulesets/Base/arraymath.jl

Closes #727 
There is separately already a `@scalar_rule` for muladd` in `base.jl`
so this just needs to handle the array cases.
I just make this the same as `rrule` accepts, and also updated tests to be as comprehensive.
Technically this rule should also work for arrays of arrays etc.
But so far noone has complained of that not being available for reverse mode, so i doubt they will for reverse mode,
If they do we can always widen it somewhat

Restrict types accepted by frule muladd and make tests more comprehensive

---

Project.toml
src/rulesets/Base/nondiff.jl

Some array types for which it is safe to assume non differrentiability of `unique`. 
I don't see the test file corresponding to the `nondiff.jl` source file. It is ok to leave these untested?
The need for these rules arised in https://github.com/CarloLucibello/GraphNeuralNetworks.jl/pull/333

non_differentiable unique

---

.JuliaFormatter.toml
.github/workflows/format.yml

This PR adds JuliaFormatter config. See https://github.com/JuliaDiff/ChainRulesCore.jl/pull/482 for more information.
I haven't formatted the current source so as not to make conflicts with other PRs.

Copy JuliaFormatter config from ChainRulesCore.jl

---

src/rulesets/Base/indexing.jl
test/rulesets/Base/indexing.jl

This are taken directly from another project.
Suprising we didn't have them already

add frules for getfield

---

src/rulesets/Base/arraymath.jl
src/rulesets/Base/base.jl
test/rulesets/Base/base.jl

This is actually the only part of [ `kf/forcedar` ](https://github.com/JuliaDiff/ChainRules.jl/blob/kf/forcedar/) that hasn't already been merged, or had code for it significantly changed (based on code that was already type pirated downstream)
Since this change is mostly written by Keno I am going to count this as already reviewed

muladd rule for zero tangent

---

test/unzipped.jl

I do not know if this is the correct fix, this is just allowing it to return either.
Some change upstream i think in julia itself (since this test only failed in 1.x not in 1.6) changed something that cause this to now return a `JLArray` not a `ReinterprettedArray`.
But I think that's fine, good even.
But idk. @mcabbott ?

Allow unzip to return JLArray

---

Project.toml
src/rulesets/Base/indexing.jl
test/rulesets/Base/indexing.jl

This fixes https://github.com/FluxML/Zygote.jl/issues/1470, which was caused by Zygote switching to the CR rule. I can't think of any scenarios where this wouldn't work and the current implementation would, so hopefully it's a non-controversial fix.

Allow single indexing of arrays of GPU arrays

---

src/rulesets/Base/nondiff.jl

Attempt at alternative to https://github.com/JuliaDiff/ChainRulesCore.jl/pull/653 for fixing https://github.com/JuliaDiff/ChainRules.jl/issues/769

Try deleting the `one(::Any)` and `zero(::Any)` non_diff methods

---

src/rulesets/LinearAlgebra/structured.jl
src/rulesets/SparseArrays/sparsematrix.jl
test/rulesets/SparseArrays/sparsematrix.jl

Bug fix for https://github.com/JuliaDiff/ChainRules.jl/issues/763: the code causing errors on non-GPL Julia builds is now wrapped in a conditional block, so it will never be executed if CHOLMOD is not available.

Fix bugs with SparseInverseSubset on non-GPL Julia builds

---

Project.toml
src/rulesets/Base/base.jl
test/rulesets/Base/base.jl

Attempt to fix the problems raised in https://github.com/SciML/NeuralPDE.jl/pull/791 that was caused by https://github.com/JuliaDiff/ChainRules.jl/pull/770
I *think* this is the right way to generalize the scalar rule to any input type, and always return a `ZeroTangent()` instead of a `NoTangent()` like the old `@non_differentiable` rule did which was quite mathematically suspect.

Use handwritten rules for `zero` and `one`

---

src/rulesets/SparseArrays/sparsematrix.jl

`SparseInverseSubset` was not being imported in Julia >=1.7.
Introduced by #772. Closes #763?

Fix `UndefVarError: sparseinv not defined` test failures

---

src/rulesets/Base/nondiff.jl

This doesn't reproduce locally for me.
And doesn't show up on never julia versions.
Possibly dispatch changed subtly to prevent this.
But lets see if it fixes it on CI

remove ambig in nondiff cumprod(::Vector{AbstractBool}) on julia 1.6

---

src/rulesets/Base/array.jl
test/rulesets/Base/array.jl

`zero_tangent` correctly handles zeros for things that do not have `zero` implemented, by using it in `_instantitate_zeros` we can support anything being passed to `vect`
Without this rule, anything with a vector being constructed is very annoying, makes Diffractor very sad.
Not sure if should go further and also knock out some of the array cases.
Especially arrays of arrays. But that can always be a follow up

support arbitary types for vect -- use zero_tangent for _instantiate_zeros

---

src/rulesets/Base/nondiff.jl

This is to match `Base.trunc` and notably is used in `convert(::Type{Int64}, ::Float64)`

Add rule for `Base.unsafe_trunc`

---

src/rulesets/Base/base.jl
test/rulesets/Base/base.jl

Based on https://github.com/LuxDL/Lux.jl/pull/659
but with some fixes up to use ChainRulesCore types.
Initial PR is not inferable.
I suspect i will need to rewrite this as a generated funcition to make it infer.
@Avik-pal do you want to test this branch against your use case, with it deleted from Lux?

Add rrule for NamedTuple merge

---

src/rulesets/LinearAlgebra/structured.jl
test/rulesets/LinearAlgebra/structured.jl

Fixes https://github.com/SciML/DiffEqFlux.jl/issues/744

Add Tridiagonal construction rule

---

.github/workflows/CI.yml

This has been stocastically failing more often than not. The signal to noise ratio is too low and i have just been ignoring it for like a year. It is some julia or JuliaInterpetter bug being hit

exclude julia 1.6 x86 from CI

---

Project.toml
src/rulesets/Base/nondiff.jl

See https://github.com/FluxML/Zygote.jl/issues/1523 for an issue this fixes.

Add @non_differentiable BitVector(::Any...)

---

.github/workflows/format.yml
Project.toml
src/rulesets/Base/indexing.jl
test/rulesets/Base/indexing.jl

Fixes #807
Added test as well. Two lines really belong in ChainRulesCore, not sure what the process for that is.

Fix computing of array element type for `∇eachslice`

---

Project.toml

This allows installing `GPUArraysCore@0.2` and other downstream packages that require it.
I've also bumped patch version, so that we can tag a release afterwards.

Add StructArrays@0.2 compat

---

Project.toml
src/rulesets/Base/indexing.jl
test/rulesets/Base/indexing.jl

This is required to make Zygote work with thunks (using this PR https://github.com/FluxML/Zygote.jl/pull/966).
MWE:
```julia
x = ones(Float32, 3, 2)
Zygote.gradient(x) do x
sum(map(norm, eachcol(x)))
end
```
Returns:
```
(Float32[0.0 0.0; 0.0 0.0; 0.0 0.0],)
```
The reason this happens is because `ZBack` no longer unthunks `Thunks` when being called (in `wrap_chainrules_output`), so [rrule for eachcol](https://github.com/JuliaDiff/ChainRules.jl/blob/e05500931b5424897d49ae184ed8e796e6e5357f/src/rulesets/Base/indexing.jl#L264) receives `dy` as:
```
Vector{ChainRulesCore.InplaceableThunk{ChainRulesCore.Thunk{ChainRules.var"#1071#1074"{Float32, SubArray{Float32, 1, Matrix{Float32}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}, Float32}}, ChainRules.var"#1070#1073"{Float32, …
```

Unthunk each element in `∇eachslice`

---

Project.toml
src/rulesets/Base/broadcast.jl
src/rulesets/Base/mapreduce.jl

Starting from https://github.com/JuliaLang/julia/pull/56409, we [no longer have](https://github.com/JuliaLang/julia/blob/e026affc3ad49ac199cf22ce05aeb412d50fcb21/base/Base_compiler.jl#L305) `Base._return_type === Core.Compiler._return_type`, and therefore `Core.Compiler._return_type` calls the wrong function on nightly, triggering an error. This PR should ensure a more stable access to this binding.

Use `_return_type` from Base, not from `Core.Compiler`

---

Project.toml
src/rulesets/Core/core.jl

Needed for closure support in 1.12 due to https://github.com/JuliaLang/julia/pull/40985

Add `Core.has_free_typevars` rule
