Project.toml
REQUIRE

merged #4 too quickly, ChainRules doesn't have a ForwardDiff dependency

remove unused ForwardDiff dependency

---

test/rules/base.jl
test/runtests.jl

I needed something to do on an airplane, so keep that in mind while assessing these tests.

Add tests for unary trigonometric functions

---

test/rules/base.jl
test/test_util.jl

Less and extension, more of a tidy up in preparation for additional tests which specialise further on the types of the differentials etc.

Tidy up tests a bit

---

Project.toml

In preparation for an initial release

Set version to 0.0.1

---

Project.toml
src/ChainRules.jl
src/rules/base.jl
src/rules/mapreduce.jl
test/rules/base.jl
test/rules/linalg/dense.jl
test/rules/mapreduce.jl
test/runtests.jl

These are all ported from Nabla.

Add a few more reduction rrules

---

src/rulesets/Base/base.jl
test/rulesets/Base/base.jl

The rules for `atan2` were wrong.
https://github.com/JuliaDiff/DiffRules.jl/blob/a9b00c81ac0d103888b124b2b9f58a7c815cebf9/src/rules.jl#L92

Fix atan2 rules

---

.travis.yml

Make travis run on more versions of Julia

Bump travis tests

---

Project.toml
test/rulesets/LinearAlgebra/factorization.jl
test/runtests.jl
test/test_util.jl

- The package changed name (and UUID). See https://github.com/JuliaDiff/FiniteDifferences.jl/issues/37

Update FDM to FiniteDifferences

---

test/rulesets/Base/base.jl
test/runtests.jl
test/test_util.jl

This tests if the derivatives are well-defined for complex arguments, too, or if they're wrongly assumed to be holomorphic.

test wirtinger derivatives with fdm too

---

test/rulesets/Base/base.jl

Simplifies out testing infastructure slightly

Switch constants over to use test_scalar

---

README.md

- Remove WIP stuff, we are looking solid
- Chain Goals to Features
- thus remove "First class complex support" as it sure doesn't feel first class right now (still a goal but not a feature right now)
- emphisize extensiability
- Explain relationship with ChainRulesCore

Update README.md for New Era

---

Project.toml

@zeptodoctor  helpfully pointed out was missing some bounds
https://github.com/JuliaRegistries/General/pull/4842#issuecomment-547360193

Add bounds

---

Project.toml
test/test_util.jl

idk how this got through CI in the first place.
But it has been making all the ChainRules core integration tests fail  since master has broken tests.

Fix test utils

---

docs/src/index.md
src/ChainRules.jl
test/rulesets/Base/base.jl
test/rulesets/Base/broadcast.jl
test/runtests.jl
test/test_util.jl

- partner to https://github.com/JuliaDiff/ChainRulesCore.jl/pull/110 (xref https://github.com/JuliaDiff/ChainRulesCore.jl/issues/113)
- requires CRC 0.6 https://github.com/JuliaRegistries/General/pull/8277
- built on top of #157 as that did half the work already (so might want to merge that first, then re-point this PR at master)

Remove `store!`, `accumulate`, `accumulate!`

---

.travis.yml

fix #160 
cf https://github.com/JuliaDocs/Documenter.jl/issues/1228

Fix docs building

---

Project.toml
test/rulesets/Base/mapreduce.jl
test/rulesets/LinearAlgebra/factorization.jl
test/rulesets/Statistics/statistics.jl
test/runtests.jl

- requires https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/20

Update to FiniteDifferences 0.9

---

Project.toml
src/rulesets/Base/base.jl

https://github.com/JuliaDiff/ChainRulesCore.jl/issues/152
Needs to have Project.toml updated after ChainRulesCore and ChainRulesTestUtils PRs are merged.

Switch to pullbacks only taking a single input

---

Project.toml
src/rulesets/Base/base.jl
test/rulesets/Base/base.jl

I really tried to find a solution for testing ldexp, however i fear finding a solution will not be possible without changing ChainRulesTestUtils.jl.

Added support for ldexp and clamp

---

src/rulesets/packages/NaNMath.jl
src/rulesets/packages/SpecialFunctions.jl

Not sure why these are here, they don't seem to do anything.

requires: remove unnecessary package loads

---

Project.toml
src/rulesets/Base/mapreduce.jl

I imagine this was an oversight (unless of course I'm missing some subtlety).

simplify sum rrule

---

Project.toml
src/rulesets/Base/arraymath.jl
test/rulesets/Base/arraymath.jl

add rules for vector-matrix and matrix-vector product

---

Project.toml

remove FD and CRTestUtils from deps

---

.gitignore
Project.toml
src/rulesets/LinearAlgebra/blas.jl
test/rulesets/Base/fastmath_able.jl
test/rulesets/LinearAlgebra/blas.jl
test/rulesets/LinearAlgebra/norm.jl
test/rulesets/LinearAlgebra/symmetric.jl

Replaces #341 
This PR includes some changes i made when checking that everything was inferrable.

Update to new version of ChainRulesTestUtils and FiniteDifferences

---

test/rulesets/Base/array.jl

array.jl autotangent

---

test/rulesets/Base/mapreduce.jl

autotangent mapreduce.jl tests

---

test/rulesets/Base/arraymath.jl
test/rulesets/Base/mapreduce.jl

arraymath.jl autotangent 

---

test/rulesets/Base/indexing.jl

indexing.jl autotangent

---

test/rulesets/Base/fastmath_able.jl

fastmath_able.jl autotangent

---

test/rulesets/Base/evalpoly.jl

evalpoly.jl autotangent

---

test/rulesets/Base/base.jl

base.jl autotangent

---

test/rulesets/LinearAlgebra/matfun.jl

matfun.jl autotangent

---

test/rulesets/LinearAlgebra/blas.jl

blas.jl autotangent

---

test/rulesets/Statistics/statistics.jl

Part of #360 
This also adds tests on 2D matrix which was missing

statistics.jl autotangent

---

test/rulesets/LinearAlgebra/norm.jl

norm.jl autotangent

---

test/rulesets/LinearAlgebra/symmetric.jl

symmetric.jl autotangent

---

test/rulesets/LinearAlgebra/structured.jl

structured.jl autotangent

---

test/rulesets/LinearAlgebra/dense.jl

dense.jl autotangent

---

test/rulesets/LinearAlgebra/factorization.jl

factorizations.jl autotangent

---

Project.toml
src/rulesets/Base/nondiff.jl

add rrule for insorted

---

Project.toml
src/rulesets/Base/nondiff.jl
test/rulesets/Base/base.jl

non_diff `typejoin` and `Base.depwarn`

---

test/rulesets/LinearAlgebra/factorization.jl

remove show X line

---

Project.toml
src/rulesets/Base/nondiff.jl

These were broken by JuliaLang/julia#37978 again.

fix `redirect_stdio` rules on nightly again

---

test/rulesets/Base/indexing.jl
test/rulesets/Base/sort.jl

Since https://github.com/JuliaDiff/FiniteDifferences.jl/pull/158 and https://github.com/JuliaDiff/FiniteDifferences.jl/pull/163 this is possible

remove redundant tangents

---

src/rulesets/LinearAlgebra/dense.jl
test/rulesets/LinearAlgebra/dense.jl

Closes https://github.com/FluxML/Zygote.jl/issues/916

Don't assume that shapes match in `dot(A,B)`

---

Project.toml
src/rulesets/Base/array.jl
test/rulesets/Base/array.jl

Found trying to run Diffractor on Flux.

Allow Colon in reshape rrule

---

Project.toml
src/rulesets/Base/base.jl
test/rulesets/Base/base.jl

Add rules for Base.literal_pow

---

Project.toml
src/rulesets/Base/array.jl
src/rulesets/Base/arraymath.jl
src/rulesets/Base/indexing.jl
src/rulesets/Base/mapreduce.jl
src/rulesets/Base/sort.jl
src/rulesets/LinearAlgebra/blas.jl
src/rulesets/LinearAlgebra/dense.jl
src/rulesets/LinearAlgebra/norm.jl

Follow up to https://github.com/JuliaDiff/ChainRulesCore.jl/pull/396
Could help with https://github.com/FluxML/Zygote.jl/issues/1030

Change argument order in InplaceableThunk

---

Project.toml
src/rulesets/Random/random.jl
test/rulesets/Random/random.jl

Backports #484  to release-0.8

Backport nondifferentiable Rng

---

.github/workflows/JuliaNightly.yml
README.md

Might need to wait a little bit until the latest nightly builds
propagate through.

reenable coverage

---

Project.toml
src/rulesets/Base/nondiff.jl

According to @mzgubic suggestion from https://github.com/JuliaDiff/ChainRules.jl/pull/506 .

use splatting in BitArray

---

Project.toml
src/rulesets/LinearAlgebra/structured.jl

unthunk in diagm

---

src/rulesets/Statistics/statistics.jl
test/rulesets/Statistics/statistics.jl

Rules for `var`, `std`

---

Project.toml
src/rulesets/Base/array.jl

Fix a bug in #559

---

.github/workflows/IntegrationTest.yml

Reopens https://github.com/JuliaDiff/ChainRules.jl/issues/318
because it is failing every time.
We should revert this once https://github.com/dpsanders/ReversePropagation.jl/issues/64 is solved

Disable ReversePropagation Integration test

---

Project.toml
src/rulesets/Base/indexing.jl
test/rulesets/Base/indexing.jl

Closes #556
~~But CRTestUtils does not seem to like this.~~ Fixed.

Rules for `eachslice`

---

Project.toml
src/rulesets/SparseArrays/sparsematrix.jl
test/rulesets/SparseArrays/sparsematrix.jl

The part of #586 concerning `findnz` only

rrule for findnz

---

Project.toml
src/rulesets/LinearAlgebra/matfun.jl
test/rulesets/LinearAlgebra/matfun.jl

Fix exp rules for some matrices

---

Project.toml
src/rulesets/Base/mapreduce.jl
test/rulesets/Base/mapreduce.jl

Delete special case for `sum(f, ::Adjoint)`

---

.github/workflows/IntegrationTest.yml

Diffractor has been broken on nightly for months now.
Til it is fixed it just adds noise to our CI

Comment out Reverse dependency test of Diffractor

---

Project.toml
src/rulesets/Base/array.jl
test/rulesets/Base/array.jl

Seems to be the minimal solution to close #627

Fix corner case for repeat

---

Project.toml
src/rulesets/Base/nondiff.jl

add a bunch of non-diff rules for Base

---

Project.toml
src/rulesets/Base/mapreduce.jl
test/rulesets/Base/mapreduce.jl

Needed for https://github.com/FluxML/Zygote.jl/pull/1253

Trivial case for `cumsum`

---

test/rulesets/LinearAlgebra/factorization.jl

In https://github.com/JuliaDiff/ChainRules.jl/pull/630#discussion_r895039382 I noted that there was a branch we had no way to hit with the tests, but I realized we could do so by calling `cholesky` on a symmetric matrix with lower storage. This PR just adds corresponding tests with no changes to the source code.

Add tests for cholesky with lower storage

---

test/rulesets/Base/broadcast.jl

Work around for https://github.com/JuliaDiff/ChainRulesCore.jl/issues/586
NOTE: I'm intentionally ignoring a version bump cause it just impacts tests.

Fix for ChainRulesCore #586

---

Project.toml
src/rulesets/Base/array.jl
test/rulesets/Base/array.jl

fix https://github.com/JuliaDiff/ChainRules.jl/issues/678

fix cat rrule

---

src/rulesets/Base/array.jl
src/rulesets/Base/base.jl
src/rulesets/Base/fastmath_able.jl
src/rulesets/Base/indexing.jl
src/rulesets/Base/mapreduce.jl
src/rulesets/LinearAlgebra/dense.jl
test/rulesets/Base/fastmath_able.jl
test/rulesets/Base/indexing.jl
test/rulesets/LinearAlgebra/factorization.jl
test/rulesets/LinearAlgebra/matfun.jl
test/rulesets/LinearAlgebra/structured.jl
test/rulesets/LinearAlgebra/symmetric.jl

Corrects some typos in the repository.

Correct some typos

---

Project.toml
src/rulesets/Core/core.jl
test/rulesets/Core/core.jl

Needed for newer versions of Julia

add rules for compilerbarrier

---

Project.toml
src/rulesets/Base/base.jl

This closes  https://github.com/JuliaDiff/ChainRules.jl/issues/725
and reverts https://github.com/JuliaDiff/ChainRules.jl/pull/187
See https://github.com/JuliaDiff/ChainRules.jl/issues/725 for justification

use ZeroTangent for derivative of zero and one

---

Project.toml
src/rulesets/Base/array.jl
src/rulesets/Base/base.jl
test/rulesets/Base/base.jl

This is the partner to https://github.com/JuliaDiff/ChainRulesCore.jl/pull/626
and requires that PR to be merged first.

Add rules needed for mutation

---

src/rulesets/Base/arraymath.jl
test/rulesets/Base/arraymath.jl

So far there was only a rule for negation, this adds a rule for subtraction (two-argument `-`).

Add missing subtract rule

---

test/rulesets/Base/base.jl

Generate the random numbers of the appropriate type. I assume the line should be repeated, not sure...

correct test muladd so that complex type is included

---

Project.toml
src/rulesets/Base/nondiff.jl

fixes https://github.com/FluxML/Zygote.jl/issues/1573

Make `Base.exponent`  non_differentiable
